# Generated by Django 5.2.16 on 2026-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('editor', '编辑'), ('reviewer', '审核者'), ('reader', '读者')], default='reader', max_length=16, verbose_name='角色'),
        ),
    ]
