from django.urls import path

from .knowledge_views import (
    AboutPageBlockListView,
    AdminAboutPageBlockDetailView,
    AdminAboutPageBlockListView,
    AdminDisciplineDetailView,
    AdminDisciplineListView,
    AdminKnowledgeRelationDetailView,
    AdminKnowledgeRelationListCreateView,
    AdminRecommendationListView,
    AdminRecommendationOverrideDetailView,
    AdminRecommendationOverrideListView,
    AdminRecommendationPolicyView,
    AdminRecommendationRefreshView,
    AdminSubdisciplineDetailView,
    AdminSubdisciplineListView,
    AdminTheoryTimelineDetailView,
    AdminTheoryTimelineListView,
    DisciplineDetailView,
    DisciplineListView,
    KnowledgeMatrixView,
    RecommendationListView,
    SubdisciplineDetailView,
    SubdisciplineListView,
    TheoryGraphView,
    TheoryTimelineListView,
)
from .lifecycle_views import AdminEntityLifecycleView
from .topic_merge_views import AdminTopicMergePreviewView, AdminTopicMergeView
from .knowledge_publication_views import AdminKnowledgePublicationStatusView, AdminKnowledgePublicationRetryView
from .editorial_revision_views import (
    AdminEditorialRevisionDetailView,
    AdminEditorialRevisionListCreateView,
    AdminEditorialRevisionPublishView,
)
from .field_assistant_views import (
    AdminFieldAssistantAdoptView,
    AdminFieldAssistantCreateView,
    AdminFieldAssistantDuplicateView,
    AdminFieldAssistantLookupView,
    AdminFieldAssistantRejectView,
)
from .enrichment_views import (
    AdminCandidateReviewDecisionView,
    AdminCandidateReviewView,
    AdminFieldEnrichmentCandidateDetailView,
    AdminFieldEnrichmentDecisionView,
    AdminFieldEnrichmentPolicyView,
    AdminFieldEnrichmentView,
    AdminNewAuthorityCandidateView,
)
from .backoffice_views import (
    AdminFunctionalHealthView,
    AdminIntakeWorkspaceView,
    AdminKnowledgeWorkspaceView,
    AdminKnowledgeObjectPreviewView,
    AdminPromptRegistryView,
    AdminProjectionRefreshView,
    AdminProjectionStatusView,
    AdminQueryLexiconTermInspectorView,
    AdminQueryLexiconWorkspaceView,
    AdminSystemStatusView,
    AdminWorkPagePreviewView,
)
from .curation_views import (
    WorkClaimCandidateDecisionView,
    WorkCurationSummaryView,
    WorkReadingPathPlacementDetailView,
    WorkReadingPathPlacementListView,
    WorkRecommendationOverrideView,
)
from .workflow_views import (
    IntakeWorkflowSectionView,
    WorkflowQueueView,
    WorkLibraryListView,
    WorkMaintenancePublicationView,
    WorkMaintenanceSectionView,
    WorkMaintenanceWorkspaceView,
)
from .workflow_suggestion_views import (
    IntakeWorkflowSuggestionView,
    MaintenanceWorkflowSuggestionView,
    ResearchCandidateVerifyView,
    ResearchLeadVerifyView,
    WorkflowSuggestionPolicyView,
)
from .viewpoint_views import ViewpointSearchView
from .research_views import (
    IntakeResearchView,
    ResearchContractView,
    ResearchEntityDecisionView,
    ResearchEntityDiscoveryView,
    ResearchGeneratedCandidateDecisionView,
    ResearchRunDetailView,
    WorkResearchView,
)
from .research_source_views import AdminResearchSourceRegistryView
from .provider_secret_views import AdminProviderSecretView
from .search_evaluation_views import (
    ClaimBenchmarkJudgmentDetailView,
    ClaimBenchmarkJudgmentListCreateView,
    SearchEvaluationRunDetailView,
    SearchEvaluationRunListCreateView,
    SearchEvaluationQueryListCreateView,
    SearchEvaluationSetDetailView,
    SearchEvaluationSetListCreateView,
)
from .views import (
    AdminAuthoritySuggestionView,
    AdminScholarDetailView,
    AdminScholarListView,
    AdminPageMappingView,
    AdminReaderRenditionPolicyView,
    AdminUsageAnalyticsView,
    AdminCoverCandidateListView,
    AdminCoverCandidateSelectView,
    AdminCoverCandidateThumbnailView,
    AdminWorkRecommendationImageView,
    AdminTheorySchoolDetailView,
    AdminTheorySchoolListView,
    AdminTopicDetailView,
    AdminTopicListView,
    CitationView,
    CleanCopyView,
    DocumentSearchView,
    GlobalSearchView,
    HotSearchView,
    OcrRuntimeSettingsView,
    PassageFocusView,
    PublicWorkCoverView,
    PublicWorkRecommendationImageView,
    PublicAssetManifestView,
    PublicPageContentView,
    PublicUsageEventView,
    ReaderSubmissionSettingsView,
    ScholarDetailView,
    ScholarListView,
    SemanticRuntimeSettingsView,
    SemanticIndexAdminView,
    SemanticIndexTestQueryView,
    SemanticSearchFeedbackView,
    SemanticSearchView,
    SiteConfigView,
    SiteStatsView,
    TheorySchoolDetailView,
    TheorySchoolListView,
    TopicDetailView,
    TopicListView,
    WorkDetailView,
    WorkListView,
)
from .theory_system_views import (
    AdminEvidenceDetailView,
    AdminEvidenceListView,
    AdminKnowledgeNodeDetailView,
    AdminKnowledgeNodeListView,
    AdminKnowledgeNodeMergePreviewView,
    AdminKnowledgeNodeMergeRollbackView,
    AdminKnowledgeNodeMergeView,
    AdminKnowledgeNodeVersionListView,
    AdminKnowledgeRelationDetailView as AdminNormalizedRelationDetailView,
    AdminKnowledgeRelationListView as AdminNormalizedRelationListView,
    AdminKnowledgeRelationVersionListView,
    AdminReadingPathDetailView,
    AdminReadingPathListView,
    AdminTheoryReviewActionView,
    AdminTheoryReviewTaskDetailView,
    AdminTheoryReviewTaskListView,
    AdminWorkNodeRelationDetailView,
    AdminWorkNodeRelationListView,
    KnowledgeNodeDetailView,
    KnowledgeNodeListView,
    LocalTheoryGraphView,
    NormalizedTimelineListView,
    PublicEvidenceFocusView,
    ReadingPathDetailView,
    ReadingPathListView,
    TheoryDisciplineDetailView,
    TheorySystemOverviewView,
)

urlpatterns = [
    path("admin/editions/<uuid:edition_id>/knowledge-status/", AdminKnowledgePublicationStatusView.as_view(), name="admin-edition-knowledge-status"),
    path("admin/knowledge-publications/status/", AdminKnowledgePublicationStatusView.as_view(), name="admin-knowledge-publication-status"),
    path("admin/knowledge-publications/<uuid:event_id>/retry/", AdminKnowledgePublicationRetryView.as_view(), name="admin-knowledge-publication-retry"),
    path(
        "admin/field-assistant/lookup/",
        AdminFieldAssistantLookupView.as_view(),
        name="admin-field-assistant-lookup",
    ),
    path(
        "admin/field-assistant/adopt/",
        AdminFieldAssistantAdoptView.as_view(),
        name="admin-field-assistant-adopt",
    ),
    path(
        "admin/field-assistant/reject/",
        AdminFieldAssistantRejectView.as_view(),
        name="admin-field-assistant-reject",
    ),
    path(
        "admin/field-assistant/create/",
        AdminFieldAssistantCreateView.as_view(),
        name="admin-field-assistant-create",
    ),
    path(
        "admin/field-assistant/duplicates/",
        AdminFieldAssistantDuplicateView.as_view(),
        name="admin-field-assistant-duplicates",
    ),
    path(
        "admin/editorial-revisions/",
        AdminEditorialRevisionListCreateView.as_view(),
        name="admin-editorial-revision-list",
    ),
    path(
        "admin/editorial-revisions/<uuid:pk>/",
        AdminEditorialRevisionDetailView.as_view(),
        name="admin-editorial-revision-detail",
    ),
    path(
        "admin/editorial-revisions/<uuid:pk>/publish/",
        AdminEditorialRevisionPublishView.as_view(),
        name="admin-editorial-revision-publish",
    ),
    path(
        "admin/workflows/queue/",
        WorkflowQueueView.as_view(),
        name="admin-workflow-queue",
    ),
    path(
        "admin/library/works/",
        WorkLibraryListView.as_view(),
        name="admin-work-library-list",
    ),
    path(
        "admin/library/works/<uuid:work_id>/",
        WorkMaintenanceWorkspaceView.as_view(),
        name="admin-work-maintenance-workspace",
    ),
    path(
        "admin/library/works/<uuid:work_id>/sections/<str:step_key>/",
        WorkMaintenanceSectionView.as_view(),
        name="admin-work-maintenance-section",
    ),
    path(
        "admin/library/works/<uuid:work_id>/publication/",
        WorkMaintenancePublicationView.as_view(),
        name="admin-work-maintenance-publication",
    ),
    path(
        "admin/intake/<uuid:item_id>/sections/<str:step_key>/",
        IntakeWorkflowSectionView.as_view(),
        name="admin-intake-workflow-section",
    ),
    path(
        "admin/intake/<uuid:item_id>/suggestions/",
        IntakeWorkflowSuggestionView.as_view(),
        name="admin-intake-workflow-suggestions",
    ),
    path(
        "admin/library/works/<uuid:work_id>/suggestions/",
        MaintenanceWorkflowSuggestionView.as_view(),
        name="admin-work-maintenance-suggestions",
    ),
    path(
        "admin/workflow-suggestion-policies/",
        WorkflowSuggestionPolicyView.as_view(),
        name="admin-workflow-suggestion-policies",
    ),
    path(
        "admin/research/candidates/<uuid:candidate_id>/verify/",
        ResearchCandidateVerifyView.as_view(),
        name="admin-research-candidate-verify",
    ),
    path(
        "admin/research/leads/verify/",
        ResearchLeadVerifyView.as_view(),
        name="admin-research-lead-verify",
    ),
    path(
        "admin/intake/<uuid:item_id>/research/",
        IntakeResearchView.as_view(),
        name="admin-intake-research",
    ),
    path(
        "admin/library/works/<uuid:work_id>/research/",
        WorkResearchView.as_view(),
        name="admin-work-research",
    ),
    path(
        "admin/research/runs/<uuid:run_id>/",
        ResearchRunDetailView.as_view(),
        name="admin-research-run-detail",
    ),
    path(
        "admin/research/entity-discovery/",
        ResearchEntityDiscoveryView.as_view(),
        name="admin-research-entity-discovery",
    ),
    path(
        "admin/research/entity-decisions/",
        ResearchEntityDecisionView.as_view(),
        name="admin-research-entity-decisions",
    ),
    path(
        "admin/research/contracts/",
        ResearchContractView.as_view(),
        name="admin-research-contracts",
    ),
    path(
        "admin/research/generated-candidates/<str:candidate_kind>/<uuid:candidate_id>/decision/",
        ResearchGeneratedCandidateDecisionView.as_view(),
        name="admin-research-generated-candidate-decision",
    ),
    path(
        "admin/works/<uuid:work_id>/curation/",
        WorkCurationSummaryView.as_view(),
        name="admin-work-curation-summary",
    ),
    path(
        "admin/works/<uuid:work_id>/claim-candidates/<uuid:claim_id>/decision/",
        WorkClaimCandidateDecisionView.as_view(),
        name="admin-work-claim-candidate-decision",
    ),
    path(
        "admin/works/<uuid:work_id>/reading-path-placements/",
        WorkReadingPathPlacementListView.as_view(),
        name="admin-work-reading-path-placement-list",
    ),
    path(
        "admin/works/<uuid:work_id>/reading-path-placements/<uuid:item_id>/",
        WorkReadingPathPlacementDetailView.as_view(),
        name="admin-work-reading-path-placement-detail",
    ),
    path(
        "admin/works/<uuid:work_id>/recommendation-overrides/<str:placement>/",
        WorkRecommendationOverrideView.as_view(),
        name="admin-work-recommendation-override",
    ),
    path(
        "admin/query-lexicon/",
        AdminQueryLexiconWorkspaceView.as_view(),
        name="admin-query-lexicon-workspace",
    ),
    path(
        "admin/query-lexicon/terms/",
        AdminQueryLexiconTermInspectorView.as_view(),
        name="admin-query-lexicon-term-inspector",
    ),
    path(
        "admin/knowledge-workspace/",
        AdminKnowledgeWorkspaceView.as_view(),
        name="admin-knowledge-workspace",
    ),
    path(
        "admin/prompt-registry/",
        AdminPromptRegistryView.as_view(),
        name="admin-prompt-registry",
    ),
    path(
        "admin/system-status/",
        AdminSystemStatusView.as_view(),
        name="admin-system-status",
    ),
    path(
        "admin/functional-health/",
        AdminFunctionalHealthView.as_view(),
        name="admin-functional-health",
    ),
    path(
        "admin/research-sources/",
        AdminResearchSourceRegistryView.as_view(),
        name="admin-research-source-registry",
    ),
    path(
        "admin/provider-secrets/",
        AdminProviderSecretView.as_view(),
        name="admin-provider-secrets",
    ),
    path(
        "admin/page-preview/editions/<uuid:edition_id>/",
        AdminWorkPagePreviewView.as_view(),
        name="admin-work-page-preview",
    ),
    path(
        "admin/knowledge-preview/<str:object_type>/<uuid:object_id>/",
        AdminKnowledgeObjectPreviewView.as_view(),
        name="admin-knowledge-object-preview",
    ),
    path(
        "admin/projection-status/<str:target_type>/<uuid:target_id>/",
        AdminProjectionStatusView.as_view(),
        name="admin-projection-status",
    ),
    path(
        "admin/projection-status/<str:target_type>/<uuid:target_id>/refresh/",
        AdminProjectionRefreshView.as_view(),
        name="admin-projection-refresh",
    ),
    path(
        "admin/intake/<uuid:item_id>/",
        AdminIntakeWorkspaceView.as_view(),
        name="admin-intake-workspace",
    ),
    path(
        "admin/candidate-review/",
        AdminCandidateReviewView.as_view(),
        name="admin-candidate-review",
    ),
    path(
        "admin/candidate-review/<str:candidate_kind>/<uuid:candidate_id>/decision/",
        AdminCandidateReviewDecisionView.as_view(),
        name="admin-candidate-review-decision",
    ),
    path(
        "admin/field-enrichment/",
        AdminFieldEnrichmentView.as_view(),
        name="admin-field-enrichment",
    ),
    path(
        "admin/field-enrichment/policies/",
        AdminFieldEnrichmentPolicyView.as_view(),
        name="admin-field-enrichment-policies",
    ),
    path(
        "admin/field-enrichment/candidates/<uuid:candidate_id>/",
        AdminFieldEnrichmentCandidateDetailView.as_view(),
        name="admin-field-enrichment-candidate-detail",
    ),
    path(
        "admin/field-enrichment/candidates/<uuid:candidate_id>/decision/",
        AdminFieldEnrichmentDecisionView.as_view(),
        name="admin-field-enrichment-candidate-decision",
    ),
    path(
        "admin/new-authority-candidates/",
        AdminNewAuthorityCandidateView.as_view(),
        name="admin-new-authority-candidates",
    ),
    path(
        "admin/authority-suggestions/",
        AdminAuthoritySuggestionView.as_view(),
        name="admin-authority-suggestions",
    ),
    path("site-config/", SiteConfigView.as_view(), name="site-config"),
    path("site-stats/", SiteStatsView.as_view(), name="site-stats"),
    path("about-blocks/", AboutPageBlockListView.as_view(), name="about-page-block-list"),
    path("knowledge-matrix/", KnowledgeMatrixView.as_view(), name="knowledge-matrix"),
    path("theory-system/overview/", TheorySystemOverviewView.as_view(), name="theory-system-overview"),
    path("theory-system/nodes/", KnowledgeNodeListView.as_view(), name="knowledge-node-list"),
    path("theory-system/nodes/<slug:slug>/", KnowledgeNodeDetailView.as_view(), name="knowledge-node-detail"),
    path(
        "theory-system/disciplines/<slug:slug>/",
        TheoryDisciplineDetailView.as_view(),
        name="theory-system-discipline-detail",
    ),
    path("theory-system/timeline/", NormalizedTimelineListView.as_view(), name="normalized-theory-timeline"),
    path("theory-system/graph/", LocalTheoryGraphView.as_view(), name="local-theory-graph"),
    path(
        "theory-system/evidence/<uuid:pk>/focus/",
        PublicEvidenceFocusView.as_view(),
        name="theory-evidence-focus",
    ),
    path("theory-system/reading-paths/", ReadingPathListView.as_view(), name="reading-path-list"),
    path(
        "theory-system/reading-paths/<slug:slug>/",
        ReadingPathDetailView.as_view(),
        name="reading-path-detail",
    ),
    path("disciplines/", DisciplineListView.as_view(), name="discipline-list"),
    path("disciplines/<slug:slug>/", DisciplineDetailView.as_view(), name="discipline-detail"),
    path("subdisciplines/", SubdisciplineListView.as_view(), name="subdiscipline-list"),
    path("subdisciplines/<slug:slug>/", SubdisciplineDetailView.as_view(), name="subdiscipline-detail"),
    path("theory-timeline/", TheoryTimelineListView.as_view(), name="theory-timeline"),
    path("theory-graph/", TheoryGraphView.as_view(), name="theory-graph"),
    path("recommendations/", RecommendationListView.as_view(), name="recommendation-list"),
    path("admin/disciplines/", AdminDisciplineListView.as_view(), name="admin-discipline-list"),
    path("admin/disciplines/<uuid:pk>/", AdminDisciplineDetailView.as_view(), name="admin-discipline-detail"),
    path("admin/subdisciplines/", AdminSubdisciplineListView.as_view(), name="admin-subdiscipline-list"),
    path("admin/subdisciplines/<uuid:pk>/", AdminSubdisciplineDetailView.as_view(), name="admin-subdiscipline-detail"),
    path(
        "admin/lifecycle/<slug:kind>/<uuid:pk>/",
        AdminEntityLifecycleView.as_view(),
        name="admin-entity-lifecycle",
    ),
    path("admin/theory-timeline/", AdminTheoryTimelineListView.as_view(), name="admin-theory-timeline-list"),
    path("admin/theory-timeline/<uuid:pk>/", AdminTheoryTimelineDetailView.as_view(), name="admin-theory-timeline-detail"),
    path("admin/recommendations/", AdminRecommendationListView.as_view(), name="admin-recommendation-list"),
    path("admin/recommendations/<str:placement>/", AdminRecommendationPolicyView.as_view(), name="admin-recommendation-policy"),
    path("admin/recommendations/<str:placement>/refresh/", AdminRecommendationRefreshView.as_view(), name="admin-recommendation-refresh"),
    path("admin/recommendation-overrides/", AdminRecommendationOverrideListView.as_view(), name="admin-recommendation-override-list"),
    path("admin/recommendation-overrides/<uuid:pk>/", AdminRecommendationOverrideDetailView.as_view(), name="admin-recommendation-override-detail"),
    path("admin/about-blocks/", AdminAboutPageBlockListView.as_view(), name="admin-about-page-block-list"),
    path("admin/about-blocks/<uuid:pk>/", AdminAboutPageBlockDetailView.as_view(), name="admin-about-page-block-detail"),
    path("admin/knowledge-relations/<str:kind>/", AdminKnowledgeRelationListCreateView.as_view(), name="admin-knowledge-relation-list"),
    path("admin/knowledge-relations/<str:kind>/<uuid:pk>/", AdminKnowledgeRelationDetailView.as_view(), name="admin-knowledge-relation-detail"),
    path(
        "admin/theory-system/nodes/",
        AdminKnowledgeNodeListView.as_view(),
        name="admin-knowledge-node-list",
    ),
    path(
        "admin/theory-system/nodes/<uuid:pk>/",
        AdminKnowledgeNodeDetailView.as_view(),
        name="admin-knowledge-node-detail",
    ),
    path(
        "admin/theory-system/nodes/<uuid:pk>/versions/",
        AdminKnowledgeNodeVersionListView.as_view(),
        name="admin-knowledge-node-versions",
    ),
    path(
        "admin/theory-system/nodes/<uuid:pk>/merge-preview/",
        AdminKnowledgeNodeMergePreviewView.as_view(),
        name="admin-knowledge-node-merge-preview",
    ),
    path(
        "admin/theory-system/nodes/<uuid:pk>/merge/",
        AdminKnowledgeNodeMergeView.as_view(),
        name="admin-knowledge-node-merge",
    ),
    path(
        "admin/theory-system/merges/<uuid:record_id>/rollback/",
        AdminKnowledgeNodeMergeRollbackView.as_view(),
        name="admin-knowledge-node-merge-rollback",
    ),
    path(
        "admin/theory-system/relations/",
        AdminNormalizedRelationListView.as_view(),
        name="admin-normalized-relation-list",
    ),
    path(
        "admin/theory-system/relations/<uuid:pk>/",
        AdminNormalizedRelationDetailView.as_view(),
        name="admin-normalized-relation-detail",
    ),
    path(
        "admin/theory-system/relations/<uuid:pk>/versions/",
        AdminKnowledgeRelationVersionListView.as_view(),
        name="admin-normalized-relation-versions",
    ),
    path(
        "admin/theory-system/work-relations/",
        AdminWorkNodeRelationListView.as_view(),
        name="admin-work-node-relation-list",
    ),
    path(
        "admin/theory-system/work-relations/<uuid:pk>/",
        AdminWorkNodeRelationDetailView.as_view(),
        name="admin-work-node-relation-detail",
    ),
    path(
        "admin/theory-system/evidence/",
        AdminEvidenceListView.as_view(),
        name="admin-theory-evidence-list",
    ),
    path(
        "admin/theory-system/evidence/<uuid:pk>/",
        AdminEvidenceDetailView.as_view(),
        name="admin-theory-evidence-detail",
    ),
    path(
        "admin/theory-system/review-tasks/",
        AdminTheoryReviewTaskListView.as_view(),
        name="admin-theory-review-task-list",
    ),
    path(
        "admin/theory-system/review-tasks/<uuid:pk>/",
        AdminTheoryReviewTaskDetailView.as_view(),
        name="admin-theory-review-task-detail",
    ),
    path(
        "admin/theory-system/review-tasks/<uuid:pk>/action/",
        AdminTheoryReviewActionView.as_view(),
        name="admin-theory-review-task-action",
    ),
    path(
        "admin/theory-system/reading-paths/",
        AdminReadingPathListView.as_view(),
        name="admin-reading-path-list",
    ),
    path(
        "admin/theory-system/reading-paths/<uuid:pk>/",
        AdminReadingPathDetailView.as_view(),
        name="admin-reading-path-detail",
    ),
    path("admin/reader-submission/", ReaderSubmissionSettingsView.as_view(), name="reader-submission-settings"),
    path("admin/ocr-runtime/", OcrRuntimeSettingsView.as_view(), name="ocr-runtime-settings"),
    path(
        "admin/semantic-runtime/",
        SemanticRuntimeSettingsView.as_view(),
        name="semantic-runtime-settings",
    ),
    path("admin/semantic-index/", SemanticIndexAdminView.as_view(), name="semantic-index-admin"),
    path(
        "admin/search-evaluations/sets/",
        SearchEvaluationSetListCreateView.as_view(),
        name="admin-search-evaluation-set-list",
    ),
    path(
        "admin/search-evaluations/sets/<uuid:pk>/",
        SearchEvaluationSetDetailView.as_view(),
        name="admin-search-evaluation-set-detail",
    ),
    path(
        "admin/search-evaluations/sets/<uuid:set_id>/queries/",
        SearchEvaluationQueryListCreateView.as_view(),
        name="admin-search-evaluation-query-list",
    ),
    path(
        "admin/search-evaluations/runs/",
        SearchEvaluationRunListCreateView.as_view(),
        name="admin-search-evaluation-run-list",
    ),
    path(
        "admin/search-evaluations/runs/<uuid:pk>/",
        SearchEvaluationRunDetailView.as_view(),
        name="admin-search-evaluation-run-detail",
    ),
    path(
        "admin/claim-benchmark/judgments/",
        ClaimBenchmarkJudgmentListCreateView.as_view(),
        name="admin-claim-benchmark-judgment-list",
    ),
    path(
        "admin/claim-benchmark/judgments/<uuid:pk>/",
        ClaimBenchmarkJudgmentDetailView.as_view(),
        name="admin-claim-benchmark-judgment-detail",
    ),
    path("admin/usage-analytics/", AdminUsageAnalyticsView.as_view(), name="admin-usage-analytics"),
    path(
        "admin/assets/<uuid:asset_id>/page-mapping/",
        AdminPageMappingView.as_view(),
        name="admin-page-mapping",
    ),
    path(
        "admin/editions/<uuid:edition_id>/reader-rendition/",
        AdminReaderRenditionPolicyView.as_view(),
        name="admin-reader-rendition-policy",
    ),
    path(
        "admin/semantic-index/test-query/",
        SemanticIndexTestQueryView.as_view(),
        name="semantic-index-test-query",
    ),
    path(
        "admin/works/<uuid:work_id>/cover-candidates/",
        AdminCoverCandidateListView.as_view(),
        name="admin-cover-candidate-list",
    ),
    path(
        "admin/works/<uuid:work_id>/recommendation-image/",
        AdminWorkRecommendationImageView.as_view(),
        name="admin-work-recommendation-image",
    ),
    path(
        "admin/works/<uuid:work_id>/cover-candidates/<uuid:candidate_id>/select/",
        AdminCoverCandidateSelectView.as_view(),
        name="admin-cover-candidate-select",
    ),
    path(
        "admin/works/<uuid:work_id>/cover-candidates/<uuid:candidate_id>/thumbnail/",
        AdminCoverCandidateThumbnailView.as_view(),
        name="admin-cover-candidate-thumbnail",
    ),
    path("admin/theory-schools/", AdminTheorySchoolListView.as_view(), name="admin-theory-school-list"),
    path("admin/theory-schools/<uuid:pk>/", AdminTheorySchoolDetailView.as_view(), name="admin-theory-school-detail"),
    path("admin/topics/", AdminTopicListView.as_view(), name="admin-topic-list"),
    path("admin/topics/<uuid:pk>/", AdminTopicDetailView.as_view(), name="admin-topic-detail"),
    path("admin/topics/<uuid:pk>/merge-preview/", AdminTopicMergePreviewView.as_view(), name="admin-topic-merge-preview"),
    path("admin/topics/<uuid:pk>/merge/", AdminTopicMergeView.as_view(), name="admin-topic-merge"),
    path("admin/scholars/", AdminScholarListView.as_view(), name="admin-scholar-list"),
    path("admin/scholars/<uuid:pk>/", AdminScholarDetailView.as_view(), name="admin-scholar-detail"),
    path("works/", WorkListView.as_view(), name="work-list"),
    path("works/<uuid:work_id>/cover/", PublicWorkCoverView.as_view(), name="public-work-cover"),
    path(
        "works/<uuid:work_id>/recommendation-image/",
        PublicWorkRecommendationImageView.as_view(),
        name="public-work-recommendation-image",
    ),
    path("works/<slug:slug>/", WorkDetailView.as_view(), name="work-detail"),
    path("theory-schools/", TheorySchoolListView.as_view(), name="theory-school-list"),
    path("theory-schools/<slug:slug>/", TheorySchoolDetailView.as_view(), name="theory-school-detail"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/<slug:slug>/", TopicDetailView.as_view(), name="topic-detail"),
    path("scholars/", ScholarListView.as_view(), name="scholar-list"),
    path("scholars/<slug:slug>/", ScholarDetailView.as_view(), name="scholar-detail"),
    path("search/", GlobalSearchView.as_view(), name="global-search"),
    path("hot-searches/", HotSearchView.as_view(), name="hot-searches"),
    path("usage-events/", PublicUsageEventView.as_view(), name="usage-events"),
    path("semantic-search/", SemanticSearchView.as_view(), name="semantic-search"),
    path("viewpoint-search/", ViewpointSearchView.as_view(), name="viewpoint-search"),
    path("semantic-search/feedback/", SemanticSearchFeedbackView.as_view(), name="semantic-search-feedback"),
    path("passages/<uuid:pk>/focus/", PassageFocusView.as_view(), name="passage-focus"),
    path("assets/<uuid:asset_id>/manifest/", PublicAssetManifestView.as_view(), name="asset-manifest"),
    path(
        "assets/<uuid:asset_id>/pages/<int:page_index>/",
        PublicPageContentView.as_view(),
        name="asset-page-content",
    ),
    path("assets/<uuid:asset_id>/search/", DocumentSearchView.as_view(), name="document-search"),
    path("editions/<uuid:edition_id>/citations/", CitationView.as_view(), name="citation"),
    path("clean-copy/", CleanCopyView.as_view(), name="clean-copy"),
]
