import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";

const api = "http://127.0.0.1:8105/api/catalog";
const scholarId = "30500000-0000-4000-8000-000000000091";
const personId = "30500000-0000-4000-8000-000000000092";

test("an editor selects, publishes and clears a scholar portrait without exposing the draft", async ({ page }) => {
  const errors: string[] = [];
  page.on("response", (response) => { if (response.status() >= 500) errors.push(`${response.status()} ${response.url()}`); });
  await page.route("**/runtime-config.js", (route) => route.fulfill({ contentType: "application/javascript", body: 'window.__SOCIAL_THEORY_LIBRARY_CONFIG__ = Object.freeze({apiBase:"http://127.0.0.1:8105/api"});' }));
  await page.goto("/login");
  await page.getByLabel("邮箱", { exact: true }).fill("curator-v305@example.test");
  await page.locator('input[name="password"]').fill("E2E-Local-Only-305-passphrase");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.goto(`/admin/scholars/${scholarId}`);
  const portrait = page.getByRole("region", { name: "学者肖像", exact: true });
  await expect(portrait.getByText("当前没有选择肖像。", { exact: true })).toBeVisible();
  await portrait.getByRole("link", { name: "从媒体库选择肖像", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`scholar=${scholarId}`));
  const imageData = await page.evaluate(() => {
    const canvas = document.createElement("canvas");
    canvas.width = 800; canvas.height = 1200;
    const context = canvas.getContext("2d")!;
    context.fillStyle = "#5b485e"; context.fillRect(0, 0, 800, 1200);
    return canvas.toDataURL("image/png").split(",")[1];
  });
  await page.getByLabel("图片文件", { exact: true }).setInputFiles({ name: "e2e-scholar-portrait.png", mimeType: "image/png", buffer: Buffer.from(imageData, "base64") });
  await page.getByLabel("图片说明", { exact: true }).fill("E2E肖像测试图片");
  await page.getByRole("button", { name: "上传图片", exact: true }).click();
  await page.getByLabel("来源名称", { exact: true }).fill("本地测试图片");
  await page.getByLabel("许可", { exact: true }).fill("本地测试使用");
  await page.getByRole("button", { name: "保存资料并生成预览", exact: true }).click();
  await expect(page.getByText("图片信息已保存。请回到使用这张图片的页面发布修改。", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "用作E2E肖像学者的肖像", exact: true }).click();
  await expect(page.getByText("肖像已保存到学者草稿。请返回学者页面核对后发布，原图片保留。", { exact: true })).toBeVisible();
  const pending = await page.request.get(`${api}/admin/scholars/${scholarId}/portrait/`);
  const pendingData = await pending.json();
  expect(pendingData.canonical_write_deferred).toBe(true);
  expect(pendingData.media.renditions).toHaveLength(3);
  expect((await page.request.get(`${api}/people/${personId}/portrait/`)).status()).toBe(404);
  await page.getByRole("link", { name: "返回学者页面", exact: true }).click();
  await expect(portrait.getByRole("img", { name: "E2E肖像测试图片", exact: true })).toBeVisible();
  await expect(portrait.getByRole("img")).toHaveJSProperty("naturalWidth", 640);
  await expect(portrait).toContainText("公开图片尚未更改");
  await mkdir("output/playwright", { recursive: true });
  await portrait.screenshot({ path: "output/playwright/scholar-portrait-draft.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await portrait.screenshot({ path: "output/playwright/scholar-portrait-mobile.png" });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByRole("button", { name: "确认并发布", exact: true }).click();
  await expect(portrait).toContainText("当前显示已保存的肖像。");
  const published = await page.request.get(`${api}/scholars/e2e-portrait-scholar/`);
  const publishedData = await published.json();
  expect(publishedData.person.portrait_media.alt_text).toBe("E2E肖像测试图片");
  expect(publishedData.person.portrait).not.toContain("private/");
  const publicImage = await page.request.get(`${api}/people/${personId}/portrait/`);
  expect(publicImage.status()).toBe(200);
  expect(publicImage.headers()["content-type"]).toBe("image/webp");
  await page.goto("/scholars/e2e-portrait-scholar");
  const image = page.getByRole("img", { name: "E2E肖像测试图片", exact: true });
  await expect(image).toBeVisible();
  await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: "output/playwright/scholar-portrait-public.png" });
  await page.goto(`/admin/scholars/${scholarId}`);
  await portrait.getByRole("button", { name: "清除肖像选择", exact: true }).click();
  await page.getByRole("button", { name: "保存清除草稿", exact: true }).click();
  await expect(portrait).toContainText("当前没有选择肖像。");
  expect((await page.request.get(`${api}/people/${personId}/portrait/`)).status()).toBe(200);
  await page.getByRole("button", { name: "确认并发布", exact: true }).click();
  await expect(portrait).toContainText("当前显示已保存的肖像。");
  expect((await page.request.get(`${api}/people/${personId}/portrait/`)).status()).toBe(404);
  expect((await page.request.get(pendingData.preview_url.replace("/api/catalog", api))).status()).toBe(200);
  expect(errors).toEqual([]);
});
