# Generated by Django 5.2.16 on 2026-07-28 10:08

import django.db.models.deletion
import ingestion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received', '已接收'), ('processing', '处理中'), ('partial', '部分完成'), ('completed', '已完成'), ('failed', '失败')], default='received', max_length=20)),
                ('source', models.CharField(default='admin', max_length=30)),
                ('expected_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(max_length=800)),
                ('file', models.FileField(max_length=1000, upload_to=ingestion.models.intake_upload_path)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('document_type_hint', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('received', '已接收'), ('validating', '校验中'), ('deduplicating', '查重中'), ('extracting', '提取中'), ('ocr', 'OCR 中'), ('metadata', '识别元数据'), ('linking', '建立关联'), ('indexing', '建立索引'), ('preparing_public_asset', '准备公开文件'), ('syncing_cloud', '同步云端'), ('ready', '可发布'), ('published', '已发布'), ('needs_review', '需要处理'), ('failed', '失败'), ('withdrawn', '已下架'), ('deleted', '已删除')], db_index=True, default='received', max_length=32)),
                ('stage_progress', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('recognized_metadata', models.JSONField(blank=True, default=dict)),
                ('processing_token', models.CharField(blank=True, db_index=True, max_length=80)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.asset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ingestion.uploadbatch')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.edition')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(max_length=40)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('worker_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_fingerprint', models.CharField(blank=True, max_length=128)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('log_excerpt', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('upload_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ingestion.uploaditem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=80)),
                ('value', models.JSONField()),
                ('source', models.CharField(max_length=120)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('selected', models.BooleanField(default=False)),
                ('upload_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_candidates', to='ingestion.uploaditem')),
            ],
        ),
        migrations.CreateModel(
            name='FieldLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=80)),
                ('locked_value', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_locks', to='catalog.edition')),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('edition', 'field_name'), name='unique_edition_field_lock')],
            },
        ),
        migrations.AddIndex(
            model_name='uploaditem',
            index=models.Index(fields=['batch', 'status'], name='ingestion_u_batch_i_c6a216_idx'),
        ),
        migrations.AddIndex(
            model_name='metadatacandidate',
            index=models.Index(fields=['upload_item', 'field_name', '-confidence'], name='ingestion_m_upload__56dfc0_idx'),
        ),
    ]
