# Generated by Django 5.2.16 on 2026-08-12 17:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_admin_redesign_state(apps, schema_editor):
    UploadItem = apps.get_model("ingestion", "UploadItem")
    MetadataCandidate = apps.get_model("ingestion", "MetadataCandidate")

    workflow_by_legacy_status = {
        "received": "uploaded",
        "validating": "preflight",
        "deduplicating": "preflight",
        "extracting": "parsing",
        "ocr": "parsing",
        "metadata": "enriching",
        "linking": "resolving",
        "needs_review": "needs_review",
        "ready": "ready",
        "indexing": "indexing",
        "preparing_public_asset": "indexing",
        "syncing_cloud": "indexing",
        "published": "published",
        "failed": "failed",
        "withdrawn": "archived",
        "deleted": "archived",
    }
    for legacy_status, workflow_state in workflow_by_legacy_status.items():
        UploadItem.objects.filter(status=legacy_status).update(
            workflow_state=workflow_state,
        )
    UploadItem.objects.update(workflow_updated_at=models.F("updated_at"))
    MetadataCandidate.objects.filter(selected=True).update(lifecycle="accepted")

    # PostgreSQL defers foreign-key trigger checks until transaction commit.
    # Django also defers indexes for the fields added above until the migration
    # schema editor exits. Flush the pending trigger events before those index
    # statements run while keeping this large migration fully atomic.
    if schema_editor is not None and schema_editor.connection.vendor == "postgresql":
        schema_editor.connection.check_constraints()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_semanticindexversion_validation'),
        ('ingestion', '0007_processingjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('text_quote', models.TextField(blank=True)),
                ('source_kind', models.CharField(db_index=True, max_length=40)),
                ('external_identifier', models.CharField(blank=True, max_length=400)),
                ('extraction_method', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=160)),
                ('model_revision', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityResolutionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(db_index=True, max_length=40)),
                ('source_name', models.CharField(max_length=500)),
                ('candidate_entity_type', models.CharField(max_length=80)),
                ('candidate_entity_id', models.CharField(blank=True, max_length=128)),
                ('label', models.CharField(max_length=500)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('supporting_properties', models.JSONField(blank=True, default=dict)),
                ('match_score', models.FloatField(default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('preview_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('proposed', '待判断'), ('linked', '已关联现有实体'), ('create_draft', '创建新实体草稿'), ('unresolved', '保留未解析名称'), ('ignored', '已忽略'), ('rejected', '已拒绝')], db_index=True, default='proposed', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-match_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=80)),
                ('operation', models.CharField(max_length=80)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('request_fingerprint', models.CharField(blank=True, max_length=128)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('provider_version', models.CharField(blank=True, max_length=80)),
                ('retrieved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '等待获取'), ('succeeded', '获取成功'), ('failed', '获取失败')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_metadata_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='conflict_group',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='lifecycle',
            field=models.CharField(choices=[('proposed', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('superseded', '已被替代')], db_index=True, default='proposed', max_length=20),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='normalized_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_metadata_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='score_factors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='error_kind',
            field=models.CharField(blank=True, choices=[('retryable', '可重试'), ('manual_intervention', '需要人工修复'), ('permanent', '永久失败')], max_length=24),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingattempt',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_attempts', to='ingestion.processingattempt'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='error_kind',
            field=models.CharField(blank=True, choices=[('retryable', '可重试'), ('manual_intervention', '需要人工修复'), ('permanent', '永久失败')], max_length=24),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='access_policy',
            field=models.CharField(choices=[('public', '公开访问'), ('registered', '登录读者'), ('restricted', '受限访问')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='ai_suggestions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='duplicate_policy',
            field=models.CharField(choices=[('review', '发现重复时人工确认'), ('block_exact', '阻止完全重复文件'), ('allow', '允许继续入库')], default='review', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='external_enrichment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='label',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='ocr_strategy',
            field=models.CharField(choices=[('auto', '自动检测'), ('force', '强制 OCR'), ('skip', '跳过 OCR')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='preflight_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='workflow_state',
            field=models.CharField(choices=[('uploaded', '已上传'), ('preflight', '预检'), ('parsing', '解析'), ('enriching', '补充元数据'), ('resolving', '实体消歧'), ('needs_review', '等待审核'), ('ready', '可以批准'), ('approved', '已批准'), ('indexing', '建立索引'), ('published', '已发布'), ('failed', '失败'), ('cancelled', '已取消'), ('archived', '已归档')], db_index=True, default='uploaded', max_length=24),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='workflow_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(
            backfill_admin_redesign_state,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='processingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_attempt_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_job_idempotency_key'),
        ),
        migrations.AddField(
            model_name='candidateevidence',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence', to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='candidateevidence',
            name='metadata_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='ingestion.metadatacandidate'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='metadata_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='ingestion.metadatacandidate'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='ingestion.uploaditem'),
        ),
        migrations.AddField(
            model_name='entityresolutioncandidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_entity_resolution_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityresolutioncandidate',
            name='upload_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_resolution_candidates', to='ingestion.uploaditem'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='resolution_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='ingestion.entityresolutioncandidate'),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ingestion_review_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_ingestion_review_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ingestion_review_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='ingestion.uploaditem'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='review_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='ingestion.reviewtask'),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='ingestion.uploaditem'),
        ),
        migrations.AddField(
            model_name='entityresolutioncandidate',
            name='source_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_resolution_candidates', to='ingestion.sourcerecord'),
        ),
        migrations.AddField(
            model_name='candidateevidence',
            name='source_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evidence', to='ingestion.sourcerecord'),
        ),
        migrations.AddField(
            model_name='metadatacandidate',
            name='source_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_candidates', to='ingestion.sourcerecord'),
        ),
        migrations.AddIndex(
            model_name='metadatacandidate',
            index=models.Index(fields=['upload_item', 'lifecycle', 'field_name'], name='ingestion_m_upload__ef8415_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='ingestion_r_status_7519de_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['target_type', 'target_id'], name='ingestion_r_target__2f9a34_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='ingestion_d_target__473dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['provider', 'operation', 'request_fingerprint'], name='ingestion_s_provide_43acf7_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['status', 'retrieved_at'], name='ingestion_s_status_e42ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='entityresolutioncandidate',
            index=models.Index(fields=['upload_item', 'target_type', 'status'], name='ingestion_e_upload__df538f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevidence',
            index=models.Index(fields=['metadata_candidate', 'source_kind'], name='ingestion_c_metadat_50b2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevidence',
            index=models.Index(fields=['asset', 'page_number'], name='ingestion_c_asset_i_661b2e_idx'),
        ),
    ]
