# Generated by Django 5.2.16 on 2026-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_knowledgenodealias_is_verified_and_more'),
        ('ingestion', '0012_alter_processingjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaditem',
            name='staging_backend',
            field=models.CharField(blank=True, choices=[('r2', 'Cloudflare R2 staging')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_cleanup_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_cleanup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_error_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_file_last_modified',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_import_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_part_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_status',
            field=models.CharField(blank=True, choices=[('uploading', '浏览器正在上传'), ('uploaded', 'R2 上传完成'), ('importing', '正在导入正式存储'), ('imported', '正式存储导入完成'), ('import_failed', '正式存储导入失败'), ('cleanup_pending', '等待清理 R2'), ('cleaned', 'R2 已清理'), ('aborted', '上传已取消'), ('expired', 'R2 staging 已过期')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_total_parts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='staging_upload_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('ocr', 'OCR'), ('external_enrichment', '联网补充'), ('text_extraction', '文本提取'), ('page_labels', '页码识别'), ('semantic_index', '语义索引'), ('query_lexicon_candidates', '术语候选提取'), ('query_lexicon_reconcile', 'QueryLexicon 重建'), ('projection_refresh', '公开投影刷新'), ('thumbnail', '缩略图'), ('cache_refresh', '公开目录刷新'), ('r2_staging', 'R2 上传中转')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='uploaditem',
            index=models.Index(fields=['staging_status', 'updated_at'], name='ingestion_u_staging_eefc6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploaditem',
            constraint=models.CheckConstraint(condition=models.Q(('staging_backend', ''), models.Q(('staging_backend', 'r2'), ('staging_object_key__startswith', 'staging/')), _connector='OR'), name='r2_staging_key_namespace'),
        ),
    ]
