# Generated by Django 5.2.16 on 2026-09-06 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_v305_cataloging_session'),
        ('ingestion', '0014_alter_entityresolutioncandidate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entityresolutioncandidate',
            name='cataloging_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_candidates', to='catalog.catalogingsession'),
        ),
        migrations.AlterField(
            model_name='entityresolutioncandidate',
            name='upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_resolution_candidates', to='ingestion.uploaditem'),
        ),
        migrations.AddIndex(
            model_name='entityresolutioncandidate',
            index=models.Index(fields=['cataloging_session', 'target_type', 'status'], name='entity_candidate_session_state'),
        ),
        migrations.AddConstraint(
            model_name='entityresolutioncandidate',
            constraint=models.CheckConstraint(condition=models.Q(('upload_item__isnull', False), ('cataloging_session__isnull', False), _connector='OR'), name='entity_candidate_has_context'),
        ),
    ]
