# Generated by Django 5.2.16 on 2026-09-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_v305_bibliographic_publication'),
        ('ingestion', '0015_v305_session_entity_candidates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacandidate',
            name='cataloging_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_candidates', to='catalog.catalogingsession'),
        ),
        migrations.AlterField(
            model_name='metadatacandidate',
            name='upload_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_candidates', to='ingestion.uploaditem'),
        ),
        migrations.AddIndex(
            model_name='metadatacandidate',
            index=models.Index(fields=['cataloging_session', 'field_name', 'lifecycle'], name='metadata_candidate_session'),
        ),
        migrations.AddConstraint(
            model_name='metadatacandidate',
            constraint=models.CheckConstraint(condition=models.Q(('upload_item__isnull', False), ('cataloging_session__isnull', False), _connector='OR'), name='metadata_candidate_has_context'),
        ),
    ]
