# Generated by Django 5.2.16 on 2026-09-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0018_discovery_index_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
