# Generated by Django 5.2.16 on 2026-08-17 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_field_enrichment'),
        ('reading', '0004_library_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymessage',
            name='query_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='librarymessage',
            name='request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='librarymessage',
            name='retrieval_profile',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='librarymessage',
            name='runtime_profile_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='librarymessagesource',
            name='document_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='librarymessagesource',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_answer_sources', to='catalog.page'),
        ),
        migrations.AddField(
            model_name='librarymessagesource',
            name='passage_language',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='librarymessagesource',
            name='reader_url_snapshot',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='librarymessagesource',
            name='retrieval_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
