# Generated by Django 5.2.16 on 2026-07-28 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(default='s3', max_length=40)),
                ('endpoint_url', models.URLField(blank=True)),
                ('bucket', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('public_base_url', models.URLField(blank=True)),
                ('credential_reference', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', '等待'), ('running', '执行中'), ('completed', '完成'), ('failed', '失败')], default='queued', max_length=20)),
                ('destination_path', models.CharField(max_length=1000)),
                ('include_originals', models.BooleanField(default=False)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudBudgetPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warning_ratio', models.FloatField(default=0.8)),
                ('stop_new_publications_ratio', models.FloatField(default=1.0)),
                ('pause_new_cdn_on_limit', models.BooleanField(default=True)),
                ('preserve_existing_reads', models.BooleanField(default=True)),
                ('notification_emails', models.JSONField(blank=True, default=list)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_policy', to='distribution.cloudprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudUsageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('egress_bytes', models.BigIntegerField(default=0)),
                ('request_count', models.BigIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='distribution.cloudprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_key', models.CharField(max_length=1000)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待同步'), ('syncing', '同步中'), ('ready', '就绪'), ('failed', '失败'), ('deleting', '删除中'), ('deleted', '已删除')], default='pending', max_length=20)),
                ('cdn_enabled', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_objects', to='catalog.asset')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cloud_objects', to='distribution.cloudprovider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'object_key'), name='unique_cloud_object_key')],
            },
        ),
    ]
