# Generated by Django 5.2.16 on 2026-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='archive_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
