# Generated by Django 5.2.16 on 2026-07-28 10:08

import catalog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='knowledge/%Y/%m/')),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('definition', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(blank=True, max_length=120)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('publication_place', models.CharField(blank=True, max_length=200)),
                ('journal_title', models.CharField(blank=True, max_length=300)),
                ('volume', models.CharField(blank=True, max_length=40)),
                ('issue', models.CharField(blank=True, max_length=40)),
                ('page_range', models.CharField(blank=True, max_length=80)),
                ('degree_institution', models.CharField(blank=True, max_length=300)),
                ('degree_type', models.CharField(blank=True, max_length=120)),
                ('report_institution', models.CharField(blank=True, max_length=300)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata_confidence', models.FloatField(default=0)),
                ('citation_data', models.JSONField(blank=True, default=dict)),
                ('canonical_filename', models.CharField(blank=True, max_length=800)),
                ('public_slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ('state', models.CharField(choices=[('draft', '草稿'), ('ready', '待发布'), ('published', '已发布'), ('withdrawn', '已下架')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('search_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('public_asset_prepared_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publication_year', 'work__title'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('configuration', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_name', models.CharField(db_index=True, max_length=240)),
                ('sort_name', models.CharField(blank=True, max_length=240)),
                ('original_name', models.CharField(blank=True, max_length=240)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, upload_to='people/%Y/%m/')),
                ('external_ids', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_name', 'preferred_name'],
            },
        ),
        migrations.CreateModel(
            name='TheorySchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='knowledge/%Y/%m/')),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('key_themes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='knowledge/%Y/%m/')),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('original', '原始文件'), ('normalized', '规范阅读文件')], max_length=20)),
                ('file', models.FileField(max_length=1000, upload_to=catalog.models.asset_upload_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('ready', '就绪'), ('failed', '失败'), ('withdrawn', '已下架')], default='pending', max_length=20)),
                ('extraction_method', models.CharField(blank=True, max_length=30)),
                ('is_current', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalog.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='从 1 开始的 PDF 页序')),
                ('printed_label', models.CharField(blank=True, max_length=40)),
                ('chapter_title', models.CharField(blank=True, max_length=600)),
                ('text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('text_source', models.CharField(choices=[('embedded', 'PDF 原生文本'), ('ocr', 'OCR'), ('hybrid', '混合')], max_length=16)),
                ('confidence', models.FloatField(default=1)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='catalog.asset')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(blank=True, db_index=True)),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('bbox_union', models.JSONField(default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='catalog.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('author', '作者'), ('editor', '编者'), ('translator', '译者'), ('advisor', '导师'), ('subject', '研究对象')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='catalog.edition')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='catalog.person')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('publish', '发布'), ('update', '更新'), ('withdraw', '下架'), ('republish', '重新发布')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_events', to='catalog.edition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScholarProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('key_concerns', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('featured_quote', models.TextField(blank=True)),
                ('quote_source', models.CharField(blank=True, max_length=500)),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholar_profile', to='catalog.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('public', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('block_type', models.CharField(default='paragraph', max_length=30)),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('bbox', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='catalog.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonKnowledgeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.concept')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations', to='catalog.person')),
                ('theory_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.theoryschool')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('book', '图书'), ('journal_article', '期刊论文'), ('thesis', '学位论文'), ('report', '研究报告')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=600)),
                ('subtitle', models.CharField(blank=True, max_length=600)),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=600)),
                ('abstract', models.TextField(blank=True)),
                ('language', models.CharField(default='zh-CN', max_length=16)),
                ('cover', models.ImageField(blank=True, upload_to='covers/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['document_type', 'normalized_title'], name='catalog_wor_documen_b98887_idx')],
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='catalog.work'),
        ),
        migrations.CreateModel(
            name='WorkKnowledgeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('theory_school', '理论流派'), ('topic', '主题'), ('concept', '概念')], max_length=24)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.concept')),
                ('theory_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.theoryschool')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.topic')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations', to='catalog.work')),
            ],
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['edition', 'kind', 'is_current'], name='catalog_ass_edition_4a4b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('sha256', 'kind'), name='unique_asset_hash_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('asset', 'index'), name='unique_page_index_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='unique_passage_order_per_page'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('edition', 'person', 'role'), name='unique_contribution'),
        ),
        migrations.AddConstraint(
            model_name='textblock',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='unique_block_order_per_page'),
        ),
        migrations.AddIndex(
            model_name='workknowledgerelation',
            index=models.Index(fields=['work', 'kind', 'approved'], name='catalog_wor_work_id_f42c78_idx'),
        ),
    ]
