# Generated by Django 5.2.16 on 2026-07-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='search_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
