# Generated by Django 5.2.16 on 2026-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_work_search_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='search_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='search_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='search_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
