# Generated by Django 5.2.16 on 2026-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_concept_search_aliases_theoryschool_search_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='curation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='curation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='topic',
            name='curation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
