import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0007_shared_media_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherAuthority",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_name", models.CharField(max_length=300, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("possible_places", models.JSONField(blank=True, default=list)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("valid_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("valid_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"ordering": ["canonical_name"]},
        ),
        migrations.CreateModel(
            name="SemanticChunk",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("page_start", models.PositiveIntegerField()),
                ("page_end", models.PositiveIntegerField()),
                ("chapter_title", models.CharField(blank=True, max_length=600)),
                ("section_title", models.CharField(blank=True, max_length=600)),
                ("paragraph_index", models.PositiveIntegerField(default=0)),
                ("original_text", models.TextField()),
                ("normalized_text", models.TextField(db_index=True)),
                ("context_before", models.TextField(blank=True)),
                ("context_after", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("document_type", models.CharField(choices=[("book", "图书"), ("journal_article", "期刊论文"), ("thesis", "学位论文"), ("report", "研究报告")], max_length=32)),
                ("parser_version", models.CharField(max_length=40)),
                ("chunk_version", models.CharField(max_length=40)),
                ("embedding_model", models.CharField(blank=True, max_length=240)),
                ("embedding_version", models.CharField(blank=True, max_length=80)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("locators", models.JSONField(blank=True, default=list)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                ("index_status", models.CharField(choices=[("pending", "待建立"), ("indexing", "索引中"), ("ready", "已建立"), ("failed", "失败")], db_index=True, default="pending", max_length=20)),
                ("index_error", models.TextField(blank=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semantic_chunks", to="catalog.asset")),
                ("work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="semantic_chunks", to="catalog.work")),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="SemanticIndexJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation", models.CharField(choices=[("build", "建立索引"), ("rebuild", "重新建立"), ("clean", "清理孤立索引"), ("test", "测试查询")], max_length=20)),
                ("status", models.CharField(choices=[("queued", "等待处理"), ("running", "处理中"), ("paused", "已暂停"), ("completed", "完成"), ("partial", "部分完成"), ("failed", "失败"), ("canceled", "已取消")], db_index=True, default="queued", max_length=20)),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("model_name", models.CharField(blank=True, max_length=240)),
                ("chunk_version", models.CharField(blank=True, max_length=40)),
                ("error_code", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="semantic_index_jobs", to="catalog.asset")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PublicationPlaceEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_value", models.CharField(blank=True, max_length=300)),
                ("normalized_value", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("province_or_state", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("place_type", models.CharField(choices=[("publication_place", "出版地"), ("production_place", "制作地"), ("distribution_place", "发行地"), ("printing_place", "印刷地"), ("publisher_address", "出版社地址"), ("degree_place", "学位授予单位所在地"), ("archive_location", "档案收藏地")], max_length=32)),
                ("source_type", models.CharField(max_length=80)),
                ("source_provider", models.CharField(blank=True, max_length=120)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("evidence_page", models.PositiveIntegerField(blank=True, null=True)),
                ("evidence_text", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0)),
                ("verification_status", models.CharField(choices=[("auto_confirmed", "自动确认"), ("needs_review", "待人工确认"), ("manually_confirmed", "人工确认"), ("manually_corrected", "人工修改"), ("unknown", "未知")], db_index=True, default="needs_review", max_length=32)),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("publisher_raw", models.CharField(blank=True, max_length=300)),
                ("publication_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("relation", models.CharField(default="publication", max_length=40)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publication_place_evidence", to="catalog.asset")),
                ("edition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publication_place_evidence", to="catalog.edition")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["display_order", "-confidence", "created_at"]},
        ),
        migrations.CreateModel(
            name="PublicationMetadataRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=40)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("edition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publication_metadata_revisions", to="catalog.edition")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SemanticSearchFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_hash", models.CharField(db_index=True, max_length=64)),
                ("query_text", models.TextField(blank=True)),
                ("relevant", models.BooleanField()),
                ("result_rank", models.PositiveSmallIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("chunk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="feedback", to="catalog.semanticchunk")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="semanticchunk",
            constraint=models.UniqueConstraint(fields=("asset", "chunk_version", "order"), name="unique_semantic_chunk_order"),
        ),
        migrations.AddIndex(model_name="semanticchunk", index=models.Index(fields=["asset", "index_status"], name="catalog_sem_asset_i_c2ce23_idx")),
        migrations.AddIndex(model_name="semanticchunk", index=models.Index(fields=["work", "page_start"], name="catalog_sem_work_id_54e289_idx")),
        migrations.AddIndex(model_name="semanticindexjob", index=models.Index(fields=["status", "created_at"], name="catalog_sem_status_0c0b32_idx")),
        migrations.AddIndex(model_name="publicationplaceevidence", index=models.Index(fields=["edition", "place_type", "verification_status"], name="catalog_pub_edition_899f2b_idx")),
        migrations.AddIndex(model_name="semanticsearchfeedback", index=models.Index(fields=["query_hash", "relevant"], name="catalog_sem_query_h_bd8769_idx")),
    ]
