# Generated by Django 5.2.16 on 2026-07-31 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_knowledge_matrix(apps, schema_editor):
    Discipline = apps.get_model("catalog", "Discipline")
    RecommendationPolicy = apps.get_model("catalog", "RecommendationPolicy")
    AboutPageBlock = apps.get_model("catalog", "AboutPageBlock")
    WorkKnowledgeRelation = apps.get_model("catalog", "WorkKnowledgeRelation")
    PersonKnowledgeRelation = apps.get_model("catalog", "PersonKnowledgeRelation")

    disciplines = [
        {
            "code": "sociology",
            "slug": "sociology",
            "name": "社会学",
            "foreign_name": "Sociology",
            "description": "从社会关系、制度与结构出发理解社会生活。",
            "sort_order": 10,
        },
        {
            "code": "anthropology",
            "slug": "anthropology",
            "name": "人类学",
            "foreign_name": "Anthropology",
            "description": "从文化、实践与比较视野理解人类生活。",
            "sort_order": 20,
        },
        {
            "code": "ethnology",
            "slug": "ethnology",
            "name": "民族学",
            "foreign_name": "Ethnology",
            "description": "研究族群、民族关系及其历史与现实变化。",
            "sort_order": 30,
        },
    ]
    for values in disciplines:
        defaults = {**values, "editorial_status": "published"}
        code = defaults.pop("code")
        Discipline.objects.update_or_create(code=code, defaults=defaults)

    policies = [
        ("home_featured", "首页精选馆藏", 4),
        ("home_theories", "首页理论传统", 4),
        ("home_scholars", "首页学者", 4),
        ("home_topics", "首页问题主题", 4),
        ("home_random", "首页随机推荐", 4),
        ("theory_weekly", "理论页本周馆藏", 4),
    ]
    for placement, title, item_count in policies:
        RecommendationPolicy.objects.update_or_create(
            placement=placement,
            defaults={
                "title": title,
                "item_count": item_count,
                "rotation_days": 3,
                "rules": {
                    "exclude_previous_cycles": 2,
                    "published_only": True,
                    "shared_for_all_readers": True,
                },
                "enabled": True,
            },
        )

    about_blocks = [
        ("about-intro", "intro", "从原文出发", "本书库面向社会科学研究与学习，提供公开阅读、全文检索、页码定位和规范引用。", 10),
        ("about-why", "intro", "为什么建设这座书库", "在研究与教学中，概念与引文被反复引用，却常常脱离原先的语境。我希望通过系统化的数字化与组织，将关键词、思想与引文重新连接回它们最初所在的页面与文本之中。", 20),
        ("about-feature-source", "feature", "寻找原始出处", "按书名、作者、概念或记得的句子进行检索，快速定位到原始文本中的确切页面。", 30),
        ("about-feature-reading", "feature", "阅读与整理", "在线阅读，记录进度，添加书签、划线与高亮，并撰写个人笔记。", 40),
        ("about-feature-knowledge", "feature", "理解知识关系", "按学者、理论传统、子学科与问题主题浏览，发现文本之间的关联。", 50),
        ("about-process", "process", "资料如何进入书库", "文件识别|元数据提取|全文处理|人工校订|正式发布", 60),
        ("about-open", "principle", "开放原则与使用边界", "提供检索与公共阅读服务，支持学习、研究与教学等合理使用。", 70),
        ("about-copyright", "principle", "版权与资源来源", "书库收录内容版权归原始权利人所有。我们遵循合理使用原则，仅提供检索与在线阅读。", 80),
        ("about-privacy", "principle", "隐私", "你的个人笔记、标注与阅读记录默认仅对你可见，不会公开或分享给任何第三方。", 90),
        ("about-notice", "notice", "请把系统结果视为阅读入口", "OCR 识别、观点检索与自动分类可能存在错误或遗漏，正式引用与学术写作请以原始页面为准。", 100),
    ]
    for key, block_type, title, body, sort_order in about_blocks:
        AboutPageBlock.objects.update_or_create(
            key=key,
            defaults={
                "block_type": block_type,
                "title": title,
                "body": body,
                "sort_order": sort_order,
                "visible": True,
            },
        )

    WorkKnowledgeRelation.objects.filter(approved=True).update(review_status="approved")
    PersonKnowledgeRelation.objects.filter(approved=True).update(review_status="approved")


def preserve_seeded_content(apps, schema_editor):
    # These rows can be edited by administrators after deployment. A rollback
    # therefore keeps them instead of deleting possible user changes.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_semantic_search_and_publication_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('search_aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='public/knowledge/%Y/%m/')),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('foreign_name', models.CharField(blank=True, max_length=240)),
                ('introduction', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('curation_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personknowledgerelation',
            name='relation_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='personknowledgerelation',
            name='review_status',
            field=models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20),
        ),
        migrations.AddField(
            model_name='personknowledgerelation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personknowledgerelation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_person_knowledge_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='core_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='curation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='entity_level',
            field=models.CharField(choices=[('tradition', '理论传统'), ('school', '流派'), ('branch', '分支')], default='tradition', max_length=20),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='foreign_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='theoryschool',
            name='formation_period',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='topic',
            name='core_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='curation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='formation_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='research_dimensions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='work',
            name='recommendation_image',
            field=models.ImageField(blank=True, upload_to='public/recommendations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='evidence_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_knowledge_evidence', to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='evidence_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='evidence_printed_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='evidence_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='review_status',
            field=models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_knowledge_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='role',
            field=models.CharField(blank=True, choices=[('foundational', '奠基文献'), ('development', '理论发展'), ('introduction', '入门综述'), ('empirical_application', '经验应用'), ('method_use', '方法使用'), ('criticism', '理论批评'), ('theory_history', '理论史研究'), ('local_mention', '局部提及')], max_length=32),
        ),
        migrations.AddField(
            model_name='workknowledgerelation',
            name='strength',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16),
        ),
        migrations.CreateModel(
            name='AboutPageBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('block_type', models.CharField(choices=[('intro', '简介'), ('stat', '数据'), ('feature', '功能'), ('process', '入库步骤'), ('principle', '开放原则'), ('notice', '提示'), ('action', '操作入口'), ('footer', '页脚信息')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('action_label', models.CharField(blank=True, max_length=120)),
                ('action_href', models.CharField(blank=True, max_length=400)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_about_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('home_featured', '首页精选馆藏'), ('home_theories', '首页理论传统'), ('home_scholars', '首页学者'), ('home_topics', '首页问题主题'), ('home_random', '首页随机推荐'), ('theory_weekly', '理论页本周馆藏')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('item_count', models.PositiveSmallIntegerField(default=4)),
                ('rotation_days', models.PositiveSmallIntegerField(default=3)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recommendation_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['placement'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('automatic', '系统轮换'), ('manual', '管理员更新')], default='automatic', max_length=16)),
                ('seed', models.CharField(blank=True, max_length=120)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendation_snapshots', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.recommendationpolicy')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Subdiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('search_aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='public/knowledge/%Y/%m/')),
                ('editorial_status', models.CharField(default='draft', max_length=20)),
                ('foreign_name', models.CharField(blank=True, max_length=240)),
                ('research_object', models.TextField(blank=True)),
                ('core_questions', models.JSONField(blank=True, default=list)),
                ('formation_period', models.CharField(blank=True, max_length=160)),
                ('research_directions', models.JSONField(blank=True, default=list)),
                ('methods', models.JSONField(blank=True, default=list)),
                ('representative_issues', models.JSONField(blank=True, default=list)),
                ('curation_level', models.PositiveSmallIntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdisciplines', to='catalog.discipline')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.subdiscipline')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('pin', '固定展示'), ('exclude', '排除展示')], max_length=12)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_overrides', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.discipline')),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.scholarprofile')),
                ('theory_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.theoryschool')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.topic')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.work')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='catalog.recommendationpolicy')),
                ('subdiscipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subdiscipline')),
            ],
            options={
                'ordering': ['policy', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('image_override', models.ImageField(blank=True, upload_to='public/recommendations/overrides/%Y/%m/')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.discipline')),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.scholarprofile')),
                ('theory_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.theoryschool')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.topic')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.work')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.recommendationsnapshot')),
                ('subdiscipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.subdiscipline')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonSubdisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdiscipline_relations', to='catalog.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_person_subdisciplines', to=settings.AUTH_USER_MODEL)),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='catalog.subdiscipline')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryDisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', '主要学科'), ('related', '相关学科')], default='related', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_relations', to='catalog.discipline')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theory_disciplines', to=settings.AUTH_USER_MODEL)),
                ('theory_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_relations', to='catalog.theoryschool')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryHierarchyRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('evidence_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='catalog.theoryschool')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='catalog.theoryschool')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theory_hierarchies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('influence', '影响'), ('continuation', '继承'), ('split', '分化'), ('critique', '批评'), ('synthesis', '综合'), ('adjacent', '相邻')], max_length=24)),
                ('strength', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_printed_label', models.CharField(blank=True, max_length=40)),
                ('evidence_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_relation_evidence', to='catalog.asset')),
                ('evidence_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_relation_evidence', to='catalog.work')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theory_relations', to=settings.AUTH_USER_MODEL)),
                ('source_theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='catalog.theoryschool')),
                ('target_theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='catalog.theoryschool')),
            ],
        ),
        migrations.CreateModel(
            name='TheorySubdisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('core', '核心理论'), ('related', '相关理论'), ('applied', '常用理论')], default='related', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theory_subdisciplines', to=settings.AUTH_USER_MODEL)),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_relations', to='catalog.subdiscipline')),
                ('theory_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdiscipline_relations', to='catalog.theoryschool')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='public/knowledge/timeline/%Y/%m/')),
                ('event_type', models.CharField(choices=[('scholar', '学者'), ('publication', '重要发表'), ('formation', '形成'), ('development', '发展'), ('debate', '争论'), ('institution', '机构')], max_length=20)),
                ('start_year', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('end_year', models.SmallIntegerField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('orientation', models.CharField(default='neutral', max_length=20)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_printed_label', models.CharField(blank=True, max_length=40)),
                ('evidence_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='catalog.discipline')),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_evidence', to='catalog.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theory_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_timeline_events', to='catalog.scholarprofile')),
                ('subdiscipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='catalog.subdiscipline')),
                ('theory_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='catalog.theoryschool')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_timeline_events', to='catalog.work')),
            ],
            options={
                'ordering': ['start_year', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TopicDisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='catalog.discipline')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topic_disciplines', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_relations', to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSubdisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topic_subdisciplines', to=settings.AUTH_USER_MODEL)),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='catalog.subdiscipline')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdiscipline_relations', to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTheoryRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topic_theories', to=settings.AUTH_USER_MODEL)),
                ('theory_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='catalog.theoryschool')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_relations', to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubdisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('strength', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_printed_label', models.CharField(blank=True, max_length=40)),
                ('evidence_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_subdiscipline_evidence', to='catalog.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_subdisciplines', to=settings.AUTH_USER_MODEL)),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='catalog.subdiscipline')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdiscipline_relations', to='catalog.work')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recommendationsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('policy',), name='unique_current_recommendation_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='unique_recommendation_position'),
        ),
        migrations.AddConstraint(
            model_name='personsubdisciplinerelation',
            constraint=models.UniqueConstraint(fields=('person', 'subdiscipline'), name='unique_person_subdiscipline'),
        ),
        migrations.AddConstraint(
            model_name='theorydisciplinerelation',
            constraint=models.UniqueConstraint(fields=('theory_school', 'discipline'), name='unique_theory_discipline'),
        ),
        migrations.AddConstraint(
            model_name='theoryhierarchyrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_theory_hierarchy'),
        ),
        migrations.AddConstraint(
            model_name='theoryrelation',
            constraint=models.UniqueConstraint(fields=('source_theory', 'target_theory', 'relation_type'), name='unique_theory_relation'),
        ),
        migrations.AddConstraint(
            model_name='theorysubdisciplinerelation',
            constraint=models.UniqueConstraint(fields=('theory_school', 'subdiscipline'), name='unique_theory_subdiscipline'),
        ),
        migrations.AddConstraint(
            model_name='topicdisciplinerelation',
            constraint=models.UniqueConstraint(fields=('topic', 'discipline'), name='unique_topic_discipline'),
        ),
        migrations.AddConstraint(
            model_name='topicsubdisciplinerelation',
            constraint=models.UniqueConstraint(fields=('topic', 'subdiscipline'), name='unique_topic_subdiscipline'),
        ),
        migrations.AddConstraint(
            model_name='topictheoryrelation',
            constraint=models.UniqueConstraint(fields=('topic', 'theory_school'), name='unique_topic_theory'),
        ),
        migrations.AddConstraint(
            model_name='worksubdisciplinerelation',
            constraint=models.UniqueConstraint(fields=('work', 'subdiscipline'), name='unique_work_subdiscipline'),
        ),
        migrations.RunPython(seed_knowledge_matrix, preserve_seeded_content),
    ]
