# Generated by Django 5.2.16 on 2026-07-31 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_knowledge_matrix_recommendations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='catalog.discipline')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_relations', to='catalog.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_person_disciplines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'discipline'), name='unique_person_discipline')],
            },
        ),
        migrations.CreateModel(
            name='WorkDisciplineRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_printed_label', models.CharField(blank=True, max_length=40)),
                ('evidence_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='catalog.discipline')),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_discipline_evidence', to='catalog.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_disciplines', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_relations', to='catalog.work')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work', 'discipline'), name='unique_work_discipline')],
            },
        ),
    ]
