# Generated by Django 5.2.16 on 2026-08-12 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_semanticindexversion_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='access_status',
            field=models.CharField(choices=[('inherit', '继承版本权限'), ('private', '仅后台可用'), ('restricted', '受限访问'), ('public', '公开访问')], db_index=True, default='inherit', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='language_guess',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='asset',
            name='rights_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='text_layer_quality',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='edition',
            name='distribution_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edition',
            name='distributor',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='edition',
            name='extent',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='edition',
            name='isbn10',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='edition',
            name='isbn13',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='edition',
            name='manufacture_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='edition',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='edition',
            name='publisher_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='catalog.publisherauthority'),
        ),
        migrations.AddField(
            model_name='edition',
            name='responsibility_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='series',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.knowledgenode'),
        ),
        migrations.AddField(
            model_name='person',
            name='authority_status',
            field=models.CharField(choices=[('draft', '草稿'), ('needs_review', '待消歧'), ('verified', '已核验'), ('rejected', '已拒绝'), ('merged', '已合并'), ('archived', '已归档')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='first_publication_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='original_language',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='work',
            name='original_title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='work',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='catalog.work'),
        ),
        migrations.AddField(
            model_name='work',
            name='uniform_title',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='node_type',
            field=models.CharField(choices=[('discipline', '学科'), ('theory_tradition', '理论传统'), ('subdiscipline', '子学科'), ('concept', '核心概念'), ('debate', '理论争论'), ('research_problem', '研究问题'), ('topic', '主题')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='knowledgenode',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='knowledge_node_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('translation_of_id')), _negated=True), name='work_translation_not_self'),
        ),
    ]
