# Generated by Django 5.2.16 on 2026-08-17 14:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_query_lexicon_candidates'),
        ('ingestion', '0011_query_lexicon_candidate_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgerelation',
            name='relation_type',
            field=models.CharField(choices=[('inherited_from', '继承'), ('revises', '修正'), ('extends', '扩展'), ('criticizes', '批判'), ('responds_to', '回应'), ('competes_with', '竞争'), ('synthesizes', '综合'), ('branches_from', '分化'), ('borrows_concept_from', '概念借用'), ('transferred_to', '跨学科传播'), ('influenced_by', '受到影响'), ('overlaps_with', '部分重叠')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EnrichmentCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('person', '人物'), ('work', '作品'), ('edition', '版本'), ('discipline', '学科'), ('subdiscipline', '子学科'), ('knowledge_node', '知识节点'), ('topic', '主题'), ('reading_path', '阅读路径')], db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=96)),
                ('candidate_kind', models.CharField(choices=[('factual', '事实'), ('classification', '分类'), ('interpretive', '解释')], db_index=True, max_length=24)),
                ('proposed_value', models.JSONField()),
                ('normalized_value', models.JSONField(blank=True, default=dict)),
                ('current_value', models.JSONField(blank=True, default=dict, null=True)),
                ('request_context', models.JSONField(blank=True, default=dict)),
                ('source_class', models.CharField(choices=[('identifier_registry', '标识符注册库'), ('publisher', '出版社'), ('national_library', '国家图书馆'), ('library_catalog', '图书馆目录'), ('university', '大学'), ('research_institute', '研究机构'), ('academic_journal', '学术期刊'), ('professional_association', '专业协会'), ('scholarly_encyclopedia', '学术百科'), ('scholar_homepage', '学者主页'), ('syllabus', '课程大纲'), ('general_web', '一般网页'), ('unknown', '未知来源')], db_index=True, default='unknown', max_length=40)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence_factors', models.JSONField(blank=True, default=dict)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('identity_status', models.CharField(choices=[('not_required', '无需身份核验'), ('confirmed', '身份已确认'), ('ambiguous', '身份存在歧义'), ('conflict', '身份冲突')], db_index=True, default='not_required', max_length=24)),
                ('identity_evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('superseded', '已被替代')], db_index=True, default='pending', max_length=20)),
                ('requested_mode', models.CharField(choices=[('structured', '结构化来源'), ('web', '联网来源'), ('full', '结构化与联网来源')], default='structured', max_length=20)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('conflict_group', models.CharField(db_index=True, max_length=64)),
                ('policy_version', models.CharField(max_length=80)),
                ('extraction_version', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('refresh_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('accepted_authority_model', models.CharField(blank=True, max_length=120)),
                ('accepted_authority_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrichment_candidates', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_enrichment_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(max_length=2000)),
                ('canonical_url', models.URLField(max_length=2000)),
                ('source_title', models.CharField(max_length=1000)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('source_class', models.CharField(choices=[('identifier_registry', '标识符注册库'), ('publisher', '出版社'), ('national_library', '国家图书馆'), ('library_catalog', '图书馆目录'), ('university', '大学'), ('research_institute', '研究机构'), ('academic_journal', '学术期刊'), ('professional_association', '专业协会'), ('scholarly_encyclopedia', '学术百科'), ('scholar_homepage', '学者主页'), ('syllabus', '课程大纲'), ('general_web', '一般网页'), ('unknown', '未知来源')], db_index=True, max_length=40)),
                ('provider', models.CharField(db_index=True, max_length=120)),
                ('external_identifier', models.CharField(blank=True, db_index=True, max_length=500)),
                ('supporting_text', models.TextField()),
                ('locator', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField(db_index=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('content_checksum', models.CharField(max_length=64)),
                ('entity_match_evidence', models.JSONField(blank=True, default=dict)),
                ('extraction_method', models.CharField(max_length=80)),
                ('extraction_version', models.CharField(max_length=80)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='catalog.enrichmentcandidate')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_evidence', to='ingestion.sourcerecord')),
            ],
            options={
                'ordering': ['-retrieved_at', 'source_title'],
            },
        ),
        migrations.AddIndex(
            model_name='enrichmentcandidate',
            index=models.Index(fields=['target_type', 'target_id', 'field_name', 'status'], name='enrich_target_field_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmentcandidate',
            index=models.Index(fields=['status', 'candidate_kind', '-confidence'], name='enrich_review_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('field_name', ''), _negated=True), models.Q(('conflict_group', ''), _negated=True)), name='enrichment_candidate_keys_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'accepted'), _negated=True), models.Q(models.Q(('accepted_authority_model', ''), _negated=True), ('accepted_authority_id__isnull', False)), _connector='OR'), name='enrichment_accept_has_authority'),
        ),
        migrations.AddIndex(
            model_name='enrichmentevidence',
            index=models.Index(fields=['candidate', 'is_current'], name='enrich_evidence_current_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmentevidence',
            index=models.Index(fields=['canonical_url', 'is_current'], name='enrich_evidence_url_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentevidence',
            constraint=models.UniqueConstraint(fields=('candidate', 'fingerprint'), name='unique_enrichment_evidence'),
        ),
        migrations.AddConstraint(
            model_name='enrichmentevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_url', ''), _negated=True), models.Q(('canonical_url', ''), _negated=True), models.Q(('source_title', ''), _negated=True), models.Q(('supporting_text', ''), _negated=True), models.Q(('content_checksum', ''), _negated=True)), name='enrichment_evidence_source_not_empty'),
        ),
    ]
