# Generated by Django 5.2.16 on 2026-08-18 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_field_enrichment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenodealias',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='knowledgenodealias',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='knowledgenodealias',
            name='source_kind',
            field=models.CharField(choices=[('editorial', '编辑确认'), ('authority_import', '权威库导入'), ('legacy_review', '历史名称复核'), ('pdf_evidence', '馆藏 PDF 证据'), ('web_evidence', '联网证据'), ('other', '其他已记录来源')], default='editorial', max_length=32),
        ),
        migrations.CreateModel(
            name='NewAuthorityCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('person', '人物'), ('knowledge_node', '知识节点'), ('topic', '主题'), ('unknown', '待判断')], db_index=True, default='unknown', max_length=32)),
                ('primary_term', models.CharField(max_length=500)),
                ('normalized_primary_term', models.CharField(db_index=True, max_length=500)),
                ('terms', models.JSONField(default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence_factors', models.JSONField(blank=True, default=dict)),
                ('possible_matches', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('matched', '已关联现有实体'), ('draft_created', '已创建草稿'), ('rejected', '已拒绝'), ('superseded', '证据已过期')], db_index=True, default='pending', max_length=24)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('matched_entity_type', models.CharField(blank=True, max_length=32)),
                ('matched_entity_id', models.UUIDField(blank=True, null=True)),
                ('draft_entity_type', models.CharField(blank=True, max_length=32)),
                ('draft_entity_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_new_authority_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnknownEntityObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('printed_page_label', models.CharField(blank=True, max_length=40)),
                ('terms', models.JSONField(default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('entity_guess', models.CharField(choices=[('person', '人物'), ('knowledge_node', '知识节点'), ('topic', '主题'), ('unknown', '待判断')], db_index=True, default='unknown', max_length=32)),
                ('evidence_text', models.TextField()),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(max_length=80)),
                ('extraction_version', models.CharField(max_length=80)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence_factors', models.JSONField(blank=True, default=dict)),
                ('source_text_checksum', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_entity_observations', to='catalog.asset')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='catalog.newauthoritycandidate')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_entity_observations', to='catalog.edition')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_entity_observations', to='catalog.page')),
                ('semantic_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_entity_observations', to='catalog.semanticchunk')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_entity_observations', to='catalog.work')),
            ],
            options={
                'ordering': ['work__title', 'page_number', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newauthoritycandidate',
            index=models.Index(fields=['status', 'entity_type', '-confidence'], name='new_authority_review_idx'),
        ),
        migrations.AddIndex(
            model_name='newauthoritycandidate',
            index=models.Index(fields=['normalized_primary_term', 'entity_type'], name='new_authority_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='newauthoritycandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('primary_term', ''), _negated=True), models.Q(('normalized_primary_term', ''), _negated=True)), name='new_authority_term_not_empty'),
        ),
        migrations.AddIndex(
            model_name='unknownentityobservation',
            index=models.Index(fields=['candidate', 'is_current'], name='unknown_obs_current_idx'),
        ),
        migrations.AddIndex(
            model_name='unknownentityobservation',
            index=models.Index(fields=['asset', 'is_current'], name='unknown_observation_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='unknownentityobservation',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gte', models.F('start_offset'))), name='unknown_observation_offsets_ordered'),
        ),
        migrations.AddConstraint(
            model_name='unknownentityobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evidence_text', ''), _negated=True), models.Q(('source_text_checksum', ''), _negated=True)), name='unknown_observation_source_not_empty'),
        ),
    ]
