# Generated by Django 5.2.16 on 2026-08-19 10:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_independent_reading_path_stages(apps, schema_editor):
    ReadingPathItem = apps.get_model("catalog", "ReadingPathItem")
    ReadingPathStage = apps.get_model("catalog", "ReadingPathStage")
    database = schema_editor.connection.alias
    stages = []
    items = []

    def flush():
        if not stages:
            return
        ReadingPathStage.objects.using(database).bulk_create(stages, batch_size=500)
        ReadingPathItem.objects.using(database).bulk_update(
            items,
            ["stage", "position"],
            batch_size=500,
        )
        stages.clear()
        items.clear()

    queryset = ReadingPathItem.objects.using(database).order_by(
        "reading_path_id",
        "reading_order",
        "created_at",
    )
    for item in queryset.iterator(chunk_size=500):
        stage = ReadingPathStage(
            reading_path_id=item.reading_path_id,
            name=item.stage_name,
            description=item.stage_description,
            position=item.reading_order,
        )
        stages.append(stage)
        item.stage_id = stage.id
        item.position = item.reading_order
        items.append(item)
        if len(stages) >= 500:
            flush()
    flush()


def restore_legacy_reading_path_fields(apps, schema_editor):
    ReadingPathItem = apps.get_model("catalog", "ReadingPathItem")
    database = schema_editor.connection.alias
    items = []
    queryset = ReadingPathItem.objects.using(database).select_related("stage").order_by("id")
    for item in queryset.iterator(chunk_size=500):
        if item.stage_id:
            item.stage_name = item.stage.name
            item.stage_description = item.stage.description
        item.reading_order = item.position
        items.append(item)
        if len(items) >= 500:
            ReadingPathItem.objects.using(database).bulk_update(
                items,
                ["stage_name", "stage_description", "reading_order"],
                batch_size=500,
            )
            items.clear()
    if items:
        ReadingPathItem.objects.using(database).bulk_update(
            items,
            ["stage_name", "stage_description", "reading_order"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_knowledgenodealias_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpathitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReadingPathStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('reading_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='catalog.readingpath')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='readingpathitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.readingpathstage'),
        ),
        migrations.RunPython(
            create_independent_reading_path_stages,
            restore_legacy_reading_path_fields,
        ),
        migrations.CreateModel(
            name='EditionWorkflowDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(choices=[('work', '作品识别'), ('bibliography', '书目与出版'), ('contributors', '责任者与身份'), ('classification', '社科分类'), ('knowledge', '理论、主题与知识关系'), ('reader', '文本与阅读文件'), ('curation', '策展定位')], max_length=24)),
                ('decision', models.CharField(choices=[('confirmed', '已确认'), ('skipped', '已跳过')], default='confirmed', max_length=16)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_edition_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_decisions', to='catalog.edition')),
            ],
            options={
                'ordering': ['edition_id', 'step_key'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'step_key'), name='unique_edition_workflow_step'), models.CheckConstraint(condition=models.Q(('step_key', 'curation'), ('decision', 'confirmed'), _connector='OR'), name='workflow_skip_only_curation')],
            },
        ),
        migrations.AddIndex(
            model_name='readingpathstage',
            index=models.Index(fields=['reading_path', 'position'], name='catalog_rea_reading_28a948_idx'),
        ),
    ]
