# Generated by Django 5.2.16 on 2026-08-20 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_admin_workflow_v280'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probe_key', models.CharField(db_index=True, max_length=120)),
                ('capability', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('healthy', '正常'), ('degraded', '降级'), ('failed', '故障'), ('recovering', '恢复中'), ('paused', '已暂停'), ('unknown', '未知')], db_index=True, default='unknown', max_length=20)),
                ('source', models.CharField(choices=[('scheduled', '定时检查'), ('manual', '人工检查'), ('recovery', '恢复复核')], default='scheduled', max_length=20)),
                ('configured', models.BooleanField(null=True)),
                ('reachable', models.BooleanField(null=True)),
                ('functional', models.BooleanField(null=True)),
                ('productive', models.BooleanField(null=True)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('error_category', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_check_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_key', models.CharField(max_length=160, unique=True)),
                ('capability', models.CharField(db_index=True, max_length=120)),
                ('probe_key', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('open', '待处理'), ('recovering', '恢复中'), ('resolved', '已恢复')], db_index=True, default='open', max_length=20)),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], default='warning', max_length=20)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('error_category', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('recovery_attempt_count', models.PositiveIntegerField(default=0)),
                ('affected_features', models.JSONField(blank=True, default=list)),
                ('probable_causes', models.JSONField(blank=True, default=list)),
                ('safe_recovery_actions', models.JSONField(blank=True, default=list)),
                ('manual_guidance', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('latest_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='catalog.healthcheckrun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_health_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', '等待'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('canceled', '取消')], db_index=True, default='queued', max_length=20)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_actions', to='catalog.healthincident')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_item_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('trigger', models.CharField(choices=[('auto_load', '页面自动研究'), ('field_change', '字段变化'), ('manual', '人工重新研究'), ('health', '健康探测')], default='auto_load', max_length=24)),
                ('status', models.CharField(choices=[('queued', '等待外部研究'), ('running', '研究中'), ('completed', '完成'), ('degraded', '部分来源不可用'), ('failed', '失败'), ('canceled', '已取消')], db_index=True, default='queued', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('context_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('context_version', models.CharField(max_length=80)),
                ('contract_version', models.CharField(max_length=80)),
                ('planner_version', models.CharField(max_length=80)),
                ('active_step', models.CharField(db_index=True, max_length=40)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=list)),
                ('local_results', models.JSONField(default=dict)),
                ('external_results', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='catalog.edition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='catalog.work')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcheckrun',
            index=models.Index(fields=['probe_key', 'started_at'], name='catalog_hea_probe_k_66f3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheckrun',
            index=models.Index(fields=['capability', 'status', 'started_at'], name='catalog_hea_capabil_65d21c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthincident',
            index=models.Index(fields=['status', 'severity', 'last_seen_at'], name='catalog_hea_status_ccf280_idx'),
        ),
        migrations.AddIndex(
            model_name='healthincident',
            index=models.Index(fields=['capability', 'status'], name='catalog_hea_capabil_125fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['status', 'created_at'], name='catalog_rec_status_ac619f_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['incident', 'status'], name='catalog_rec_inciden_f56349_idx'),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['status', 'created_at'], name='catalog_res_status_504f11_idx'),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['work', 'active_step', 'created_at'], name='catalog_res_work_id_975d02_idx'),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['context_fingerprint', 'created_at'], name='catalog_res_context_e99702_idx'),
        ),
    ]
