# Generated by Django 5.2.16 on 2026-08-23 21:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


ROLE_MAP = {
    'foundational': 'foundational_work',
    'development': 'theoretical_development',
    'introduction': 'systematic_exposition',
    'empirical_application': 'empirical_application',
    'method_use': 'empirical_application',
    'criticism': 'critique',
    'theory_history': 'systematic_exposition',
    'local_mention': 'general_mention',
    '': 'general_mention',
}


def backfill_confirmed_canonical_relations(apps, schema_editor):
    """Copy known legacy relations without deleting or guessing legacy data."""

    LegacyKnowledgeMapping = apps.get_model('catalog', 'LegacyKnowledgeMapping')
    TheorySchool = apps.get_model('catalog', 'TheorySchool')
    Concept = apps.get_model('catalog', 'Concept')
    KnowledgeNodeAlias = apps.get_model('catalog', 'KnowledgeNodeAlias')
    WorkKnowledgeRelation = apps.get_model('catalog', 'WorkKnowledgeRelation')
    PersonKnowledgeRelation = apps.get_model('catalog', 'PersonKnowledgeRelation')
    WorkNodeRelation = apps.get_model('catalog', 'WorkNodeRelation')
    PersonNodeRelation = apps.get_model('catalog', 'PersonNodeRelation')
    EvidenceSnippet = apps.get_model('catalog', 'EvidenceSnippet')
    WorkTopicRelation = apps.get_model('catalog', 'WorkTopicRelation')
    PersonTopicRelation = apps.get_model('catalog', 'PersonTopicRelation')
    TheorySubdisciplineRelation = apps.get_model('catalog', 'TheorySubdisciplineRelation')
    TopicTheoryRelation = apps.get_model('catalog', 'TopicTheoryRelation')
    KnowledgeNodeSubdiscipline = apps.get_model('catalog', 'KnowledgeNodeSubdiscipline')
    KnowledgeNodeTopic = apps.get_model('catalog', 'KnowledgeNodeTopic')

    expected_node_types = {
        'TheorySchool': 'theory_tradition',
        'Concept': 'concept',
    }
    legacy_models = {
        'TheorySchool': TheorySchool,
        'Concept': Concept,
    }

    def normalized_identity(value):
        return ''.join(character for character in str(value or '').casefold() if character.isalnum())

    mapping = {}
    for row in (
        LegacyKnowledgeMapping.objects.filter(migration_status='mapped')
        .select_related('node')
        .iterator()
    ):
        expected_type = expected_node_types.get(row.legacy_model)
        if not expected_type or row.node.node_type != expected_type:
            continue
        # A mapped flag predates 3.0 and is not sufficient proof of identity.
        # Only a published target with the same canonical name or a verified
        # alias is safe for an automatic canonical relation backfill.
        if row.node.status != 'published':
            continue
        legacy = legacy_models[row.legacy_model].objects.filter(pk=row.legacy_id).first()
        if legacy is None:
            continue
        legacy_identity = normalized_identity(legacy.name)
        accepted_identities = {
            normalized_identity(row.node.canonical_name_zh),
            normalized_identity(row.node.canonical_name_en),
        }
        accepted_identities.update(
            normalized_identity(value)
            for value in KnowledgeNodeAlias.objects.filter(
                node_id=row.node_id,
                is_verified=True,
            ).values_list('alias', flat=True)
        )
        accepted_identities.discard('')
        if not legacy_identity or legacy_identity not in accepted_identities:
            continue
        mapping[(row.legacy_model, str(row.legacy_id))] = row.node_id

    for relation in WorkKnowledgeRelation.objects.order_by('created_at').iterator():
        if not relation.approved or relation.review_status != 'approved':
            continue
        if relation.kind == 'topic' and relation.topic_id:
            WorkTopicRelation.objects.get_or_create(
                work_id=relation.work_id,
                topic_id=relation.topic_id,
                defaults={
                    'is_primary': relation.is_primary,
                    'strength': relation.strength,
                    'source': relation.source,
                    'confidence': relation.confidence,
                    'evidence_asset_id': relation.evidence_asset_id,
                    'evidence_page': relation.evidence_page,
                    'evidence_printed_label': relation.evidence_printed_label,
                    'evidence_text': relation.evidence_text,
                    'review_status': relation.review_status,
                    'reviewed_by_id': relation.reviewed_by_id,
                    'reviewed_at': relation.reviewed_at,
                },
            )
            continue

        legacy_model = None
        legacy_id = None
        if relation.kind == 'theory_school' and relation.theory_school_id:
            legacy_model = 'TheorySchool'
            legacy_id = relation.theory_school_id
        elif relation.kind == 'concept' and relation.concept_id:
            legacy_model = 'Concept'
            legacy_id = relation.concept_id
        if not legacy_model:
            continue
        node_id = mapping.get((legacy_model, str(legacy_id)))
        if not node_id:
            continue
        work_node_relation, _created = WorkNodeRelation.objects.get_or_create(
            work_id=relation.work_id,
            node_id=node_id,
            role=ROLE_MAP.get(relation.role, 'general_mention'),
            defaults={
                'is_primary': relation.is_primary,
                'strength': relation.strength,
                'confidence': relation.confidence,
                'status': 'published',
                'source': relation.source,
                'reviewed_by_id': relation.reviewed_by_id,
                'reviewed_at': relation.reviewed_at,
            },
        )
        if (
            relation.evidence_asset_id
            and relation.evidence_page
            and relation.evidence_text
        ):
            EvidenceSnippet.objects.get_or_create(
                work_id=relation.work_id,
                file_id=relation.evidence_asset_id,
                node_id=node_id,
                work_node_relation_id=work_node_relation.id,
                page_number=relation.evidence_page,
                defaults={
                    'printed_page_label': relation.evidence_printed_label,
                    'quote': relation.evidence_text,
                    'extraction_method': 'manual',
                    'semantic_confidence': relation.confidence,
                    'review_status': 'approved',
                    'reviewed_by_id': relation.reviewed_by_id,
                    'reviewed_at': relation.reviewed_at,
                },
            )

    for relation in PersonKnowledgeRelation.objects.order_by('created_at').iterator():
        if not relation.approved or relation.review_status != 'approved':
            continue
        if relation.topic_id:
            PersonTopicRelation.objects.get_or_create(
                person_id=relation.person_id,
                topic_id=relation.topic_id,
                defaults={
                    # Legacy approval confirms the relation, not primacy.
                    # Do not invent a primary Topic placement during backfill.
                    'is_primary': False,
                    'relation_label': relation.relation_label,
                    'source': relation.source,
                    'confidence': relation.confidence,
                    'review_status': relation.review_status,
                    'reviewed_by_id': relation.reviewed_by_id,
                    'reviewed_at': relation.reviewed_at,
                },
            )
        for legacy_model, legacy_id in (
            ('TheorySchool', relation.theory_school_id),
            ('Concept', relation.concept_id),
        ):
            if not legacy_id:
                continue
            node_id = mapping.get((legacy_model, str(legacy_id)))
            if not node_id:
                continue
            PersonNodeRelation.objects.get_or_create(
                person_id=relation.person_id,
                node_id=node_id,
                defaults={
                    'relation_label': relation.relation_label,
                    'is_representative': relation.approved,
                    'confidence': relation.confidence,
                    'status': 'published',
                    'source': relation.source,
                    'reviewed_by_id': relation.reviewed_by_id,
                    'reviewed_at': relation.reviewed_at,
                },
            )

    for relation in TheorySubdisciplineRelation.objects.order_by('created_at').iterator():
        if relation.review_status != 'approved':
            continue
        node_id = mapping.get(('TheorySchool', str(relation.theory_school_id)))
        if not node_id:
            continue
        KnowledgeNodeSubdiscipline.objects.get_or_create(
            node_id=node_id,
            subdiscipline_id=relation.subdiscipline_id,
            defaults={
                'is_primary': relation.role == 'core',
                'relation_role': relation.role,
                'source': relation.source,
                'confidence': relation.confidence,
                'status': 'published',
                'reviewed_by_id': relation.reviewed_by_id,
                'reviewed_at': relation.reviewed_at,
            },
        )

    for relation in TopicTheoryRelation.objects.order_by('created_at').iterator():
        if relation.review_status != 'approved':
            continue
        node_id = mapping.get(('TheorySchool', str(relation.theory_school_id)))
        if not node_id:
            continue
        KnowledgeNodeTopic.objects.get_or_create(
            node_id=node_id,
            topic_id=relation.topic_id,
            defaults={
                'relation_label': relation.relation_label,
                'status': 'published',
                'reviewed_by_id': relation.reviewed_by_id,
                'reviewed_at': relation.reviewed_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_healthcheckrun_healthincident_recoveryaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalObjectRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.UUIDField(db_index=True)),
                ('current_revision', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id'), name='unique_canonical_object_revision')],
            },
        ),
        migrations.CreateModel(
            name='CapabilityExecutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executor_id', models.CharField(max_length=160, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=240)),
                ('kind', models.CharField(choices=[('nas', 'NAS'), ('remote_gpu', '远程 GPU'), ('cloud', '云端')], max_length=20)),
                ('capabilities', models.JSONField(default=list)),
                ('model_revisions', models.JSONField(blank=True, default=dict)),
                ('concurrency', models.PositiveSmallIntegerField(default=1)),
                ('current_load', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('draining', '停止接单')], db_index=True, default='offline', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'heartbeat_expires_at'], name='catalog_cap_status_de269f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DerivedClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposition', models.TextField()),
                ('subject', models.CharField(blank=True, max_length=600)),
                ('predicate', models.CharField(blank=True, max_length=300)),
                ('object', models.TextField(blank=True)),
                ('polarity', models.CharField(choices=[('positive', '肯定'), ('negative', '否定'), ('mixed', '混合'), ('uncertain', '不确定')], default='uncertain', max_length=20)),
                ('modality', models.CharField(blank=True, max_length=120)),
                ('qualifiers', models.JSONField(blank=True, default=list)),
                ('temporal_scope', models.JSONField(blank=True, default=dict)),
                ('geographic_scope', models.JSONField(blank=True, default=dict)),
                ('population_scope', models.JSONField(blank=True, default=dict)),
                ('attribution', models.CharField(choices=[('author_claim', '作者主张'), ('quoted_claim', '引述主张'), ('reported_claim', '转述主张'), ('criticized_claim', '被批评主张'), ('historical_description', '历史描述'), ('uncertain', '归因不确定')], db_index=True, default='uncertain', max_length=32)),
                ('claim_type', models.CharField(choices=[('assertion', '论断'), ('causal', '因果'), ('definition', '定义'), ('evaluation', '评价'), ('comparison', '比较'), ('mechanism', '机制'), ('interpretation', '解释'), ('criticism', '批评'), ('response', '回应')], db_index=True, max_length=24)),
                ('prompt_key', models.CharField(max_length=160)),
                ('prompt_version', models.CharField(max_length=120)),
                ('model_provider', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=240)),
                ('model_revision', models.CharField(blank=True, max_length=160)),
                ('quality_factors', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('importance_score', models.FloatField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('cluster_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', '有效'), ('stale', '待重算'), ('superseded', '已取代'), ('rejected', '已拒绝')], db_index=True, default='active', max_length=20)),
                ('shadow', models.BooleanField(db_index=True, default=True)),
                ('stale_reason', models.CharField(blank=True, max_length=240)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_claims', to='catalog.edition')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_claims', to='catalog.work')),
            ],
            options={
                'ordering': ['-importance_score', '-quality_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuratedClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('core_viewpoint', '核心观点'), ('major_criticism', '主要批评'), ('major_response', '主要回应'), ('debate_position', '争论立场')], db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('proposition', models.TextField()),
                ('editorial_note', models.TextField(blank=True)),
                ('qualifiers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('superseded', '已取代')], db_index=True, default='draft', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curated_claims', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_claims', to='catalog.knowledgenode')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_curated_claims', to=settings.AUTH_USER_MODEL)),
                ('scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_claims', to='catalog.scholarprofile')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_claims', to='catalog.topic')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_claims', to='catalog.work')),
                ('adopted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_adoptions', to='catalog.derivedclaim')),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('parser_name', models.CharField(blank=True, max_length=120)),
                ('parser_version', models.CharField(blank=True, max_length=120)),
                ('extraction_method', models.CharField(blank=True, max_length=120)),
                ('extraction_version', models.CharField(blank=True, max_length=120)),
                ('ocr_provider', models.CharField(blank=True, max_length=120)),
                ('ocr_model', models.CharField(blank=True, max_length=240)),
                ('ocr_version', models.CharField(blank=True, max_length=160)),
                ('source_checksum', models.CharField(db_index=True, max_length=64)),
                ('text_checksum', models.CharField(db_index=True, max_length=64)),
                ('quality_summary', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_revisions', to='catalog.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.CharField(default='deterministic', max_length=120)),
                ('assessor_version', models.CharField(max_length=120)),
                ('reader_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fulltext_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('semantic_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('claim_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('structure_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ocr_quality', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('critical_pages', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='catalog.documentrevision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='derivedclaim',
            name='document_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_claims', to='catalog.documentrevision'),
        ),
        migrations.CreateModel(
            name='DomainChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.UUIDField(db_index=True)),
                ('canonical_revision', models.PositiveBigIntegerField()),
                ('change_kind', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('publish', '发布'), ('withdraw', '下架'), ('delete', '删除')], max_length=20)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_change_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('work', '作品'), ('knowledge_node', '知识节点'), ('scholar_profile', '学者'), ('topic', '主题'), ('reading_path', '阅读路径')], db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('base_revision', models.PositiveBigIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField()),
                ('patch', models.JSONField(default=dict)),
                ('materialized_preview', models.JSONField(default=dict)),
                ('changed_fields', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('superseded', '已取代')], db_index=True, default='draft', max_length=20)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('change_note', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_editorial_revisions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_editorial_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_type', 'target_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField(db_index=True)),
                ('printed_page_label', models.CharField(blank=True, max_length=40)),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('original_text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('section', models.CharField(blank=True, max_length=600)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('quality', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('extraction_method', models.CharField(blank=True, max_length=120)),
                ('ocr_provenance', models.JSONField(blank=True, default=dict)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('stale_reason', models.CharField(blank=True, max_length=240)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_spans', to='catalog.documentrevision')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_spans', to='catalog.page')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_spans', to='catalog.passage')),
                ('text_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_spans', to='catalog.textblock')),
            ],
            options={
                'ordering': ['page_number', 'start_offset'],
            },
        ),
        migrations.AddField(
            model_name='derivedclaim',
            name='primary_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_claims', to='catalog.evidencespan'),
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', '主要依据'), ('supports', '支持'), ('opposes', '相斥'), ('qualifies', '限定'), ('attribution', '归因')], default='supports', max_length=20)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('curated_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='catalog.curatedclaim')),
                ('derived_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='catalog.derivedclaim')),
                ('evidence_span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='catalog.evidencespan')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeSubdiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('relation_role', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('confidence', models.FloatField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdiscipline_links', to='catalog.knowledgenode')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_node_subdisciplines', to=settings.AUTH_USER_MODEL)),
                ('subdiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_node_links', to='catalog.subdiscipline')),
            ],
            options={
                'ordering': ['sort_order', 'subdiscipline__name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('confidence', models.FloatField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='catalog.knowledgenode')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_node_topics', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_node_links', to='catalog.topic')),
            ],
            options={
                'ordering': ['sort_order', 'topic__name'],
            },
        ),
        migrations.CreateModel(
            name='PersonTopicRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('relation_label', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='catalog.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_person_topics', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.UUIDField(db_index=True)),
                ('projection_type', models.CharField(choices=[('query_lexicon', 'QueryLexicon'), ('fulltext', '全文'), ('semantic', '语义'), ('claim_index', 'Claim Index'), ('knowledge_graph', '知识关系'), ('timeline', '时间轴'), ('recommendation', '推荐'), ('reading_path_support', '阅读路径支持'), ('public', '公网呈现')], db_index=True, max_length=40)),
                ('source_revision', models.PositiveBigIntegerField(default=0)),
                ('projected_revision', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('current', '最新'), ('stale', '落后'), ('projecting', '更新中'), ('waiting_for_capability', '等待执行能力'), ('failed', '失败'), ('unknown', '待核实')], db_index=True, default='unknown', max_length=32)),
                ('stale_reason', models.CharField(blank=True, max_length=300)),
                ('task_owner_type', models.CharField(blank=True, max_length=80)),
                ('task_owner_key', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_projected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'projection_type', 'updated_at'], name='catalog_pro_status_46e02f_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id', 'projection_type'), name='unique_object_projection_state'), models.CheckConstraint(condition=models.Q(('source_revision__gte', models.F('projected_revision'))), name='projection_revision_not_ahead')],
            },
        ),
        migrations.CreateModel(
            name='WorkTopicRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('strength', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=16)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_printed_label', models.CharField(blank=True, max_length=40)),
                ('evidence_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('suggested', '系统建议'), ('approved', '人工确认'), ('rejected', '人工拒绝')], db_index=True, default='suggested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_topic_evidence', to='catalog.asset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_topics', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_relations', to='catalog.topic')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relations', to='catalog.work')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(db_index=True, max_length=80)),
                ('owner_key', models.CharField(db_index=True, max_length=255)),
                ('capability', models.CharField(db_index=True, max_length=80)),
                ('state', models.CharField(choices=[('waiting_for_capability', '等待执行能力'), ('ready', '可领取'), ('claimed', '已领取'), ('completed', '已完成'), ('failed', '失败'), ('canceled', '已取消')], db_index=True, default='waiting_for_capability', max_length=32)),
                ('priority', models.SmallIntegerField(default=0)),
                ('publication_blocking', models.BooleanField(default=False)),
                ('preferred_queue', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('lease_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.TextField(blank=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_demands', to='catalog.capabilityexecutor')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['state', 'capability', '-priority', 'created_at'], name='catalog_cap_state_c16453_idx'), models.Index(fields=['owner_type', 'owner_key'], name='catalog_cap_owner_t_06d661_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='curatedclaim',
            index=models.Index(fields=['work', 'status', 'kind', 'sort_order'], name='catalog_cur_work_id_331265_idx'),
        ),
        migrations.AddIndex(
            model_name='curatedclaim',
            index=models.Index(fields=['node', 'status', 'kind', 'sort_order'], name='catalog_cur_node_id_4509da_idx'),
        ),
        migrations.AddConstraint(
            model_name='curatedclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('scholar__isnull', True), ('topic__isnull', True), ('work__isnull', False)), models.Q(('node__isnull', False), ('scholar__isnull', True), ('topic__isnull', True), ('work__isnull', True)), models.Q(('node__isnull', True), ('scholar__isnull', False), ('topic__isnull', True), ('work__isnull', True)), models.Q(('node__isnull', True), ('scholar__isnull', True), ('topic__isnull', False), ('work__isnull', True)), _connector='OR'), name='curated_claim_has_target'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['asset', 'is_active', '-revision'], name='catalog_doc_asset_i_d6e04c_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('asset', 'revision'), name='unique_document_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset',), name='unique_active_document_revision'),
        ),
        migrations.AddConstraint(
            model_name='documentqualityassessment',
            constraint=models.UniqueConstraint(fields=('document_revision', 'assessor', 'assessor_version'), name='unique_document_quality_assessment'),
        ),
        migrations.AddIndex(
            model_name='domainchangeevent',
            index=models.Index(fields=['processed_at', 'next_attempt_at', 'created_at'], name='catalog_dom_process_53cd78_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainchangeevent',
            constraint=models.UniqueConstraint(fields=('object_type', 'object_id', 'canonical_revision'), name='unique_domain_object_revision'),
        ),
        migrations.AddIndex(
            model_name='editorialrevision',
            index=models.Index(fields=['target_type', 'target_id', 'status', '-revision'], name='catalog_edi_target__52fd19_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialrevision',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id', 'revision'), name='unique_editorial_target_revision'),
        ),
        migrations.AddIndex(
            model_name='evidencespan',
            index=models.Index(fields=['document_revision', 'page_number', 'is_stale'], name='catalog_evi_documen_3dbfe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.UniqueConstraint(fields=('document_revision', 'page', 'content_hash', 'start_offset', 'end_offset'), name='unique_revision_evidence_span'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gte', models.F('start_offset'))), name='evidence_span_offsets_ordered'),
        ),
        migrations.AddIndex(
            model_name='derivedclaim',
            index=models.Index(fields=['work', 'status', 'shadow', '-importance_score'], name='catalog_der_work_id_dc73c8_idx'),
        ),
        migrations.AddIndex(
            model_name='derivedclaim',
            index=models.Index(fields=['claim_type', 'attribution', 'polarity'], name='catalog_der_claim_t_eb5a63_idx'),
        ),
        migrations.AddConstraint(
            model_name='derivedclaim',
            constraint=models.UniqueConstraint(fields=('document_revision', 'fingerprint'), name='unique_claim_per_document_revision'),
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('derived_claim__isnull', False), ('curated_claim__isnull', True)), models.Q(('derived_claim__isnull', True), ('curated_claim__isnull', False)), _connector='OR'), name='claim_evidence_exactly_one_claim'),
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('derived_claim__isnull', False)), fields=('derived_claim', 'evidence_span', 'role'), name='unique_derived_claim_evidence_role'),
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('curated_claim__isnull', False)), fields=('curated_claim', 'evidence_span', 'role'), name='unique_curated_claim_evidence_role'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenodesubdiscipline',
            constraint=models.UniqueConstraint(fields=('node', 'subdiscipline'), name='unique_knowledge_node_subdiscipline'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenodetopic',
            constraint=models.UniqueConstraint(fields=('node', 'topic'), name='unique_knowledge_node_topic'),
        ),
        migrations.AddConstraint(
            model_name='persontopicrelation',
            constraint=models.UniqueConstraint(fields=('person', 'topic'), name='unique_person_topic'),
        ),
        migrations.AddConstraint(
            model_name='worktopicrelation',
            constraint=models.UniqueConstraint(fields=('work', 'topic'), name='unique_work_topic'),
        ),
        migrations.RunPython(
            backfill_confirmed_canonical_relations,
            migrations.RunPython.noop,
        ),
    ]
