# Generated by Django 5.2.16 on 2026-08-23 22:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_v3_knowledge_data_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_profile_key', models.CharField(db_index=True, max_length=120)),
                ('task_profile_version', models.PositiveIntegerField(default=1)),
                ('retrieval_profile', models.CharField(max_length=80)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('envelope_snapshot', models.JSONField(default=list)),
                ('retrieval_snapshot', models.JSONField(default=dict)),
                ('query_lexicon_revision', models.CharField(blank=True, max_length=160)),
                ('semantic_index_uid', models.CharField(blank=True, max_length=255)),
                ('document_revisions', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_packs', to=settings.AUTH_USER_MODEL)),
                ('research_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_packs', to='catalog.researchrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('canonical_question', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('quality_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('importance_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('conflict_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('corroboration_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('adopted', '已采用'), ('rejected', '已拒绝'), ('deferred', '稍后处理')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_debate_candidates', to=settings.AUTH_USER_MODEL)),
                ('suggested_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_candidates', to='catalog.knowledgenode')),
                ('evidence_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_candidates', to='catalog.evidencepack')),
            ],
            options={
                'ordering': ['-importance_score', '-quality_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_profile_key', models.CharField(db_index=True, max_length=120)),
                ('task_profile_version', models.PositiveIntegerField(default=1)),
                ('provider', models.CharField(blank=True, db_index=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=240)),
                ('prompt_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('candidate_type', models.CharField(db_index=True, max_length=80)),
                ('candidate_id', models.CharField(db_index=True, max_length=160)),
                ('decision', models.CharField(choices=[('accept', '采用'), ('accept_with_edit', '修改后采用'), ('reject', '拒绝'), ('defer', '稍后处理')], db_index=True, max_length=24)),
                ('original_payload', models.JSONField(blank=True, default=dict)),
                ('edited_payload', models.JSONField(blank=True, default=dict)),
                ('field_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('capability', models.CharField(db_index=True, max_length=80)),
                ('task_profile_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('content', models.TextField()),
                ('output_schema', models.JSONField(default=dict)),
                ('provider_guidance', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('schema_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('retired', '停用')], db_index=True, default='draft', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_prompt_registry_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_registry_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPathCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('target_audience', models.CharField(max_length=300)),
                ('learning_goal', models.TextField()),
                ('stages', models.JSONField(default=list)),
                ('quality_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('importance_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', '待处理'), ('adopted', '已采用'), ('rejected', '已拒绝'), ('deferred', '稍后处理')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('adopted_reading_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidates', to='catalog.readingpath')),
                ('evidence_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_path_candidates', to='catalog.evidencepack')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reading_path_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importance_score', '-quality_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTaskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=240)),
                ('required_context', models.JSONField(default=list)),
                ('retrieval_profile', models.CharField(max_length=80)),
                ('preferred_evidence_sources', models.JSONField(default=list)),
                ('minimum_evidence_policy', models.JSONField(default=dict)),
                ('prompt_key', models.CharField(max_length=160)),
                ('output_schema', models.JSONField(default=dict)),
                ('ranking_policy', models.JSONField(default=dict)),
                ('human_review_policy', models.JSONField(default=dict)),
                ('required_capability', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_research_task_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ClaimBenchmarkJudgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_relation', models.CharField(choices=[('direct', '直接回应'), ('support', '支持'), ('oppose', '相斥'), ('qualify', '限定'), ('critique', '批评'), ('extend', '延伸'), ('reframe', '重构问题')], db_index=True, max_length=20)),
                ('expected_attribution', models.CharField(choices=[('author_claim', '作者主张'), ('quoted_claim', '引述主张'), ('reported_claim', '转述主张'), ('criticized_claim', '被批评主张'), ('historical_description', '历史描述'), ('uncertain', '归因不确定')], default='uncertain', max_length=32)),
                ('relevance', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('locator_verified', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_claim_benchmark_judgments', to=settings.AUTH_USER_MODEL)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_judgments', to='catalog.documentrevision')),
                ('evidence_span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_judgments', to='catalog.evidencespan')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_judgments', to='catalog.searchevaluationquery')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_benchmark_judgments', to='catalog.work')),
            ],
            options={
                'ordering': ['query__order', '-relevance', 'created_at'],
                'indexes': [models.Index(fields=['query', 'expected_relation', 'relevance'], name='catalog_cla_query_i_f43ee4_idx')],
                'constraints': [models.UniqueConstraint(fields=('query', 'evidence_span'), name='unique_claim_benchmark_judgment')],
            },
        ),
        migrations.CreateModel(
            name='DebateCandidateClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stance', models.CharField(choices=[('support', '支持'), ('oppose', '相斥'), ('qualify', '限定')], max_length=16)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='catalog.debatecandidate')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debate_candidate_links', to='catalog.derivedclaim')),
            ],
            options={
                'ordering': ['stance', 'rank', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'claim'), name='unique_debate_candidate_claim')],
            },
        ),
        migrations.AddIndex(
            model_name='evidencepack',
            index=models.Index(fields=['task_profile_key', 'created_at'], name='catalog_evi_task_pr_235390_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencepack',
            index=models.Index(fields=['subject_type', 'subject_id', 'created_at'], name='catalog_evi_subject_395388_idx'),
        ),
        migrations.AddIndex(
            model_name='debatecandidate',
            index=models.Index(fields=['status', '-importance_score', 'created_at'], name='catalog_deb_status_6e8c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencefeedback',
            index=models.Index(fields=['task_profile_key', 'decision', 'created_at'], name='catalog_int_task_pr_975c14_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligencefeedback',
            index=models.Index(fields=['provider', 'prompt_key', 'decision'], name='catalog_int_provide_9e9e1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencefeedback',
            constraint=models.UniqueConstraint(fields=('candidate_type', 'candidate_id', 'reviewed_by'), name='unique_intelligence_candidate_feedback'),
        ),
        migrations.AddConstraint(
            model_name='promptregistryentry',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='unique_prompt_registry_entry_version'),
        ),
        migrations.AddConstraint(
            model_name='promptregistryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('key',), name='unique_active_prompt_registry_entry'),
        ),
        migrations.AddIndex(
            model_name='readingpathcandidate',
            index=models.Index(fields=['status', '-importance_score', 'created_at'], name='catalog_rea_status_5f368d_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchtaskprofile',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='unique_research_task_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='researchtaskprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('key',), name='unique_active_research_task_profile'),
        ),
    ]
