# Generated by Django 5.2.16 on 2026-08-28 10:25

import django.db.models.deletion
import hashlib
import json
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_confirmed_draft_bundles(apps, schema_editor):
    """Recover the publication context, never publish or accept legacy data."""
    alias = schema_editor.connection.alias
    Edition = apps.get_model("catalog", "Edition")
    Bundle = apps.get_model("catalog", "PublicationBundle")
    Item = apps.get_model("catalog", "PublicationBundleItem")
    Profile = apps.get_model("catalog", "ScholarProfile")
    human_sources = {"workflow_section_confirmation", "workflow_legacy_identity_adapter", "manual_cataloging", "editorial"}
    for edition in Edition.objects.using(alias).filter(state="draft").select_related("work"):
        selected = {}
        for relation in edition.contributions.filter(approved=True, source__in=human_sources).select_related("person"):
            if relation.person.authority_status in {"draft", "needs_review"}:
                selected[("person", relation.person_id)] = (relation.person, relation, relation.person.preferred_name)
        for relation in edition.work.topic_relations.filter(review_status="approved").select_related("topic"):
            if relation.topic.editorial_status in {"draft", "pending"} and (relation.source in human_sources or (relation.reviewed_by_id and relation.reviewed_at)):
                selected[("topic", relation.topic_id)] = (relation.topic, relation, relation.topic.name)
        for relation in edition.work.node_relations.filter(status__in=["pending", "published"]).select_related("node"):
            if relation.node.status in {"draft", "pending"} and (relation.source in human_sources or (relation.reviewed_by_id and relation.reviewed_at)):
                selected[("knowledge_node", relation.node_id)] = (relation.node, relation, relation.node.canonical_name_zh or relation.node.canonical_name_en)
        for relation in edition.work.knowledge_relations.filter(approved=True, review_status="approved").select_related("theory_school", "topic"):
            if not (relation.source in human_sources or (relation.reviewed_by_id and relation.reviewed_at)):
                continue
            kind, entity = ("theory_school", relation.theory_school) if relation.theory_school_id else ("topic", relation.topic)
            if entity is not None and entity.editorial_status in {"draft", "pending"}:
                selected[(kind, entity.pk)] = (entity, relation, entity.name)
        if not selected:
            continue
        bundle, _created = Bundle.objects.using(alias).get_or_create(
            context_type="edition", context_id=edition.pk, status="draft",
            defaults={"edition_id": edition.pk, "label": edition.work.title},
        )
        for (kind, identifier), (entity, relation, label) in selected.items():
            if kind == "person":
                Profile.objects.using(alias).get_or_create(
                    person_id=identifier, defaults={"slug": f"person-{identifier.hex}", "editorial_status": "draft"},
                )
            Item.objects.using(alias).get_or_create(
                bundle_id=bundle.pk, object_type=kind, object_id=identifier,
                defaults={"action": "create", "label": str(label or ""), "minimum_complete": bool(str(label or "").strip()),
                          "snapshot": {"status": "draft", "source": "v304_confirmed_draft_migration",
                                       "confirmed_relation_model": relation._meta.label, "confirmed_relation_id": str(relation.pk),
                                       "confirmed_relation_source": relation.source},
                          "blockers": [] if str(label or "").strip() else ["名称不能为空"]},
            )


def backfill_published_catalog_revisions(apps, schema_editor):
    Edition = apps.get_model("catalog", "Edition")
    PublisherAuthority = apps.get_model("catalog", "PublisherAuthority")
    CatalogFieldDecision = apps.get_model("catalog", "CatalogFieldDecision")
    ScholarProfile = apps.get_model("catalog", "ScholarProfile")
    CuratedClaim = apps.get_model("catalog", "CuratedClaim")
    CatalogPublicationRevision = apps.get_model(
        "catalog", "CatalogPublicationRevision"
    )
    now = timezone.now()
    # Publisher records predate an explicit editorial state. Preserve them as
    # formal records; 3.0.4 creates new publishers as drafts and promotes them
    # only with the current catalog publication bundle.
    PublisherAuthority.objects.update(editorial_status="published")
    scholar_slugs = dict(ScholarProfile.objects.filter(editorial_status="published").values_list("person_id", "slug"))
    for edition in Edition.objects.filter(state="published").select_related("work"):
        asset = (
            edition.assets.filter(
                kind="normalized",
                is_current=True,
                status="ready",
            )
            .order_by("-version", "-created_at")
            .first()
        )
        document_revision = None
        fulltext_ready = False
        if asset is not None:
            document_revision = (
                asset.document_revisions.filter(is_active=True)
                .order_by("-revision")
                .first()
            )
            if document_revision is not None:
                assessment = (
                    document_revision.quality_assessments.order_by("-created_at")
                    .first()
                )
                fulltext_ready = bool(
                    assessment is not None
                    and float(assessment.fulltext_quality or 0) >= 0.55
                    and float(assessment.semantic_quality or 0) >= 0.50
                )
        contributors = list(
            edition.contributions.filter(approved=True)
            .select_related("person")
            .order_by("order", "created_at")
        )
        disciplines = list(
            edition.work.discipline_relations.filter(
                review_status="approved", discipline__editorial_status="published",
            )
            .select_related("discipline")
            .order_by("-is_primary", "discipline_id")
        )
        subdisciplines = list(
            edition.work.subdiscipline_relations.filter(
                review_status="approved", subdiscipline__editorial_status="published",
            )
            .select_related("subdiscipline")
            .order_by("-is_primary", "subdiscipline_id")
        )
        topics = list(
            edition.work.topic_relations.filter(
                review_status="approved", topic__editorial_status="published",
            )
            .select_related("topic")
            .order_by("-is_primary", "topic_id")
        )
        nodes = list(
            edition.work.node_relations.filter(status="published", node__status="published")
            .select_related("node")
            .order_by("-is_primary", "node_id", "role")
        )
        snapshot = {
            "curated_claim_ids": [str(value) for value in CuratedClaim.objects.filter(
                work_id=edition.work_id, status="published",
            ).order_by("kind", "sort_order", "id").values_list("id", flat=True)],
            "work": {
                "id": str(edition.work_id),
                "title": edition.work.title,
                "subtitle": edition.work.subtitle,
                "original_title": edition.work.original_title,
                "uniform_title": edition.work.uniform_title,
                "document_type": edition.work.document_type,
                "language": edition.work.language,
                "original_language": edition.work.original_language,
                "abstract": edition.work.abstract,
                "first_publication_date": (
                    edition.work.first_publication_date.isoformat()
                    if edition.work.first_publication_date
                    else None
                ),
                "translation_of_id": (
                    str(edition.work.translation_of_id)
                    if edition.work.translation_of_id
                    else None
                ),
                "cover": str(edition.work.cover.name or ""),
                "recommendation_image": str(
                    edition.work.recommendation_image.name or ""
                ),
            },
            "edition": {
                "id": str(edition.id),
                "version_label": edition.version_label,
                "publication_date": (
                    edition.publication_date.isoformat()
                    if edition.publication_date
                    else None
                ),
                "publication_year": edition.publication_year,
                "publisher": edition.publisher,
                "publisher_authority_id": (
                    str(edition.publisher_authority_id)
                    if edition.publisher_authority_id
                    else None
                ),
                "publication_place": edition.publication_place,
                "distribution_place": edition.distribution_place,
                "distributor": edition.distributor,
                "manufacture_place": edition.manufacture_place,
                "manufacturer": edition.manufacturer,
                "journal_title": edition.journal_title,
                "volume": edition.volume,
                "issue": edition.issue,
                "page_range": edition.page_range,
                "isbn": edition.isbn,
                "isbn10": edition.isbn10,
                "isbn13": edition.isbn13,
                "doi": edition.doi,
                "series": edition.series,
                "extent": edition.extent,
                "responsibility_statement": edition.responsibility_statement,
                "public_slug": edition.public_slug,
                "state": edition.state,
            },
            "contributions": [
                {
                    "person_id": str(row.person_id),
                    "name": row.person.preferred_name,
                    "person": {
                        "id": str(row.person_id),
                        "preferred_name": row.person.preferred_name,
                        "original_name": row.person.original_name,
                        "aliases": list(row.person.aliases or []),
                        "authority_status": row.person.authority_status,
                        "birth_year": row.person.birth_year,
                        "death_year": row.person.death_year,
                        "biography": row.person.biography,
                        "portrait": str(row.person.portrait.name or ""),
                        "scholar_slug": scholar_slugs.get(row.person_id),
                    },
                    "role": row.role,
                    "order": row.order,
                }
                for row in contributors
            ],
            "classification": {
                "disciplines": [
                    {
                        "id": str(row.discipline_id),
                        "name": row.discipline.name,
                        "slug": row.discipline.slug,
                        "is_primary": row.is_primary,
                    }
                    for row in disciplines
                ],
                "subdisciplines": [
                    {
                        "id": str(row.subdiscipline_id),
                        "name": row.subdiscipline.name,
                        "slug": row.subdiscipline.slug,
                        "is_primary": row.is_primary,
                    }
                    for row in subdisciplines
                ],
            },
            "knowledge": {
                "topics": [
                    {
                        "id": str(row.topic_id),
                        "name": row.topic.name,
                        "slug": row.topic.slug,
                        "is_primary": row.is_primary,
                    }
                    for row in topics
                ],
                "nodes": [
                    {
                        "id": str(row.node_id),
                        "name": (
                            row.node.canonical_name_zh
                            or row.node.canonical_name_en
                        ),
                        "foreign_name": row.node.canonical_name_en,
                        "slug": row.node.slug,
                        "type": row.node.node_type,
                        "role": row.role,
                        "is_primary": row.is_primary,
                    }
                    for row in nodes
                ],
            },
            "document": {
                "asset_id": str(asset.id) if asset else None,
                "asset_sha256": asset.sha256 if asset else "",
                "document_revision_id": (
                    str(document_revision.id) if document_revision else None
                ),
                "document_revision": (
                    document_revision.revision if document_revision else None
                ),
                "text_checksum": (
                    document_revision.text_checksum if document_revision else ""
                ),
                "quality_ready": fulltext_ready,
            },
        }
        fingerprint = hashlib.sha256(
            json.dumps(
                snapshot,
                ensure_ascii=False,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest()
        revision = CatalogPublicationRevision.objects.create(
            edition=edition,
            revision=1,
            status="active",
            snapshot=snapshot,
            changed_fields=["legacy_published_snapshot"],
            related_entities=[],
            document_revision=document_revision,
            reader_asset=asset,
            metadata_ready=True,
            fulltext_ready=fulltext_ready,
            provenance={
                "source": "v304_safe_backfill",
                "automatic_relations_changed": False,
                "fulltext_index_revision_id": "legacy",
                "semantic_index_revision_id": "legacy",
                "claim_index_revision_id": "legacy",
            },
            content_fingerprint=fingerprint,
            activated_at=edition.last_published_at or edition.published_at or now,
        )
        Edition.objects.filter(pk=edition.pk).update(
            active_catalog_revision=revision,
            metadata_ready_at=edition.last_published_at or edition.published_at or now,
            fulltext_ready_at=(now if fulltext_ready else None),
            intelligence_status=("active" if fulltext_ready else "processing"),
        )
        field_values = {
            "file": str(asset.id) if asset else None,
            "title": edition.work.title,
            "document_type": edition.work.document_type,
            "language": edition.work.language,
            "authors": [
                {
                    "id": str(row.person_id),
                    "name": row.person.preferred_name,
                    "role": row.role,
                }
                for row in contributors
                if row.role == "author"
            ],
            "translators": [
                {
                    "id": str(row.person_id),
                    "name": row.person.preferred_name,
                    "role": row.role,
                }
                for row in contributors
                if row.role == "translator"
            ],
            "publisher": edition.publisher,
            "publication_year": edition.publication_year,
            "journal_title": edition.journal_title,
            "volume": edition.volume,
            "issue": edition.issue,
            "degree_institution": edition.degree_institution,
            "report_institution": edition.report_institution,
            "topics": [
                {"id": str(row.topic_id), "name": row.topic.name}
                for row in topics
            ],
            "theories": [
                {
                    "id": str(row.node_id),
                    "name": row.node.canonical_name_zh or row.node.canonical_name_en,
                }
                for row in nodes
            ],
        }
        for field_name, value in field_values.items():
            if value in (None, "", [], {}):
                continue
            CatalogFieldDecision.objects.get_or_create(
                context_type="edition",
                context_id=edition.id,
                target_type="edition",
                target_id=edition.id,
                field_name=field_name,
                defaults={
                    "edition_id": edition.id,
                    "status": "confirmed",
                    "value": value,
                    "previous_value": value,
                    "provenance": {"source": "v304_safe_backfill"},
                    "confirmation_method": "migrated",
                    "confirmed_at": edition.last_published_at or edition.published_at or now,
                },
            )


def noop_reverse(apps, schema_editor):
    # The reverse schema operations remove the new records and columns.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_providercredentialsecret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='fulltext_ready_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='intelligence_status',
            field=models.CharField(choices=[('draft', '草稿'), ('processing', '智能内容处理中'), ('active', '已进入智能检索'), ('failed', '智能处理异常'), ('withdrawn', '已退出智能检索')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='edition',
            name='metadata_ready_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherauthority',
            name='editorial_status',
            field=models.CharField(db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='role',
            field=models.CharField(choices=[('author', '作者'), ('chief_editor', '主编'), ('editor', '编者'), ('translator', '译者'), ('annotator', '校注'), ('photographer', '摄影'), ('advisor', '导师'), ('subject', '研究对象'), ('other', '其他贡献者')], max_length=20),
        ),
        migrations.AlterField(
            model_name='editorialrevision',
            name='target_type',
            field=models.CharField(choices=[('work', '作品'), ('edition', '版本'), ('knowledge_node', '知识节点'), ('scholar_profile', '学者'), ('discipline', '学科'), ('subdiscipline', '子学科'), ('topic', '主题'), ('publisher', '出版社'), ('reading_path', '阅读路径')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='querylexiconchangeevent',
            name='entity_type',
            field=models.CharField(choices=[('work', '作品'), ('person', '人物'), ('knowledge_node', '知识节点'), ('discipline', '学科'), ('theory_school', '理论流派'), ('topic', '主题'), ('concept', '概念'), ('subdiscipline', '子学科')], max_length=32),
        ),
        migrations.AlterField(
            model_name='querylexiconentry',
            name='entity_type',
            field=models.CharField(choices=[('work', '作品'), ('person', '人物'), ('knowledge_node', '知识节点'), ('discipline', '学科'), ('theory_school', '理论流派'), ('topic', '主题'), ('concept', '概念'), ('subdiscipline', '子学科')], max_length=32),
        ),
        migrations.AlterField(
            model_name='querylexiconentry',
            name='source_kind',
            field=models.CharField(choices=[('work_field', '正式作品字段'), ('authority_field', '权威字段'), ('person_name_variant', '结构化人物名称'), ('knowledge_node_alias', '结构化知识别名'), ('legacy_authority_field', '旧权威字段'), ('legacy_mixed_alias', '历史混合别名'), ('generated_search_variant', '机器检索变体')], max_length=40),
        ),
        migrations.AlterField(
            model_name='semanticchunk',
            name='document_type',
            field=models.CharField(choices=[('book', '图书'), ('journal_article', '期刊论文'), ('journal_issue', '整期期刊'), ('thesis', '学位论文'), ('report', '研究报告')], max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='document_type',
            field=models.CharField(choices=[('book', '图书'), ('journal_article', '期刊论文'), ('journal_issue', '整期期刊'), ('thesis', '学位论文'), ('report', '研究报告')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CatalogPublicationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('preparing', '准备中'), ('active', '活动'), ('superseded', '已取代'), ('failed', '处理失败'), ('withdrawn', '已撤回')], db_index=True, default='preparing', max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('related_entities', models.JSONField(blank=True, default=list)),
                ('metadata_ready', models.BooleanField(db_index=True, default=False)),
                ('fulltext_ready', models.BooleanField(db_index=True, default=False)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=120)),
                ('failure_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_publication_revisions', to=settings.AUTH_USER_MODEL)),
                ('document_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_publication_revisions', to='catalog.documentrevision')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_revisions', to='catalog.edition')),
                ('reader_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_publication_revisions', to='catalog.asset')),
            ],
            options={
                'ordering': ['edition_id', '-revision'],
            },
        ),
        migrations.AddField(
            model_name='domainchangeevent',
            name='catalog_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_change_events', to='catalog.catalogpublicationrevision'),
        ),
        migrations.AddField(
            model_name='edition',
            name='active_catalog_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_editions', to='catalog.catalogpublicationrevision'),
        ),
        migrations.CreateModel(
            name='KnowledgePublicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('catalog_published', '馆藏发布'), ('catalog_updated', '馆藏更新'), ('catalog_withdrawn', '馆藏撤回'), ('entity_published', '实体发布'), ('entity_updated', '实体更新'), ('entity_merged', '实体合并')], db_index=True, max_length=32)),
                ('object_type', models.CharField(db_index=True, max_length=48)),
                ('object_id', models.UUIDField(db_index=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('related_entities', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败'), ('dead_letter', '需要人工处理')], db_index=True, default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_publication_events', to=settings.AUTH_USER_MODEL)),
                ('catalog_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_events', to='catalog.catalogpublicationrevision')),
                ('domain_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_publication_event', to='catalog.domainchangeevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeProjectionDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.CharField(choices=[('query_lexicon', '规范词典'), ('bibliographic_search', '书目搜索'), ('fulltext', '全文搜索'), ('semantic', '语义检索'), ('rag', '馆藏问答材料'), ('viewpoint', '观点检索'), ('knowledge_graph', '知识关系'), ('person_search', '人物搜索'), ('recommendation', '推荐'), ('public_cache', '公开缓存')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败'), ('skipped', '无需处理')], db_index=True, default='pending', max_length=20)),
                ('source_revision', models.PositiveBigIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=220, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('last_error_message', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='catalog.knowledgepublicationevent')),
            ],
            options={
                'ordering': ['event_id', 'consumer'],
            },
        ),
        migrations.CreateModel(
            name='PublicationBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.CharField(db_index=True, max_length=48)),
                ('context_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('publishing', '发布处理中'), ('published', '已发布'), ('failed', '发布失败'), ('abandoned', '已放弃')], db_index=True, default='draft', max_length=20)),
                ('minimum_completeness', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publication_bundles', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_bundles', to='catalog.edition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_publication_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='catalogpublicationrevision',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_revisions', to='catalog.publicationbundle'),
        ),
        migrations.CreateModel(
            name='CatalogFieldDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.CharField(db_index=True, max_length=48)),
                ('context_id', models.UUIDField(db_index=True)),
                ('target_type', models.CharField(db_index=True, max_length=48)),
                ('target_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('empty', '未填写'), ('suggested', '有建议'), ('needs_review', '需要确认'), ('confirmed', '已确认'), ('conflict', '存在冲突'), ('not_applicable', '不适用'), ('stale', '建议重新检查')], db_index=True, default='empty', max_length=24)),
                ('value', models.JSONField(blank=True, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('evidence_summary', models.JSONField(blank=True, default=list)),
                ('candidate_type', models.CharField(blank=True, max_length=48)),
                ('candidate_id', models.UUIDField(blank=True, null=True)),
                ('dependency_fields', models.JSONField(blank=True, default=list)),
                ('dependency_fingerprint', models.CharField(blank=True, max_length=64)),
                ('stale_reason', models.CharField(blank=True, max_length=500)),
                ('confirmation_method', models.CharField(choices=[('manual', '人工填写'), ('candidate', '采用建议'), ('inline_create', '新建并关联'), ('migrated', '历史迁移')], default='manual', max_length=24)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_field_decisions', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_decisions', to='catalog.edition')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_decisions', to='catalog.publicationbundle')),
            ],
            options={
                'ordering': ['context_type', 'context_id', 'target_type', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationBundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(db_index=True, max_length=48)),
                ('object_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('create', '新建'), ('update', '更新'), ('link', '关联'), ('merge', '合并'), ('withdraw', '撤回')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('minimum_complete', models.BooleanField(default=False)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.publicationbundle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFieldDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=40)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('candidate_type', models.CharField(blank=True, max_length=48)),
                ('candidate_id', models.UUIDField(blank=True, null=True)),
                ('source_summary', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_field_decision_logs', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='catalog.catalogfielddecision')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', 'created_at'], name='catalog_cat_decisio_2eb389_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgepublicationevent',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='catalog_kno_status_53d121_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepublicationevent',
            index=models.Index(fields=['object_type', 'object_id', 'created_at'], name='catalog_kno_object__1d545a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeprojectiondelivery',
            index=models.Index(fields=['status', 'consumer', 'updated_at'], name='catalog_kno_status_c61f39_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeprojectiondelivery',
            constraint=models.UniqueConstraint(fields=('event', 'consumer'), name='unique_knowledge_projection_delivery'),
        ),
        migrations.AddIndex(
            model_name='publicationbundle',
            index=models.Index(fields=['status', 'updated_at'], name='catalog_pub_status_8cfb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationbundle',
            index=models.Index(fields=['edition', 'status'], name='catalog_pub_edition_c3ed06_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicationbundle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('context_type', 'context_id'), name='one_draft_publication_bundle'),
        ),
        migrations.AddIndex(
            model_name='catalogpublicationrevision',
            index=models.Index(fields=['edition', 'status', '-revision'], name='catalog_cat_edition_1362cd_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogpublicationrevision',
            index=models.Index(fields=['status', 'metadata_ready', 'fulltext_ready'], name='catalog_cat_status_6f09fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogpublicationrevision',
            constraint=models.UniqueConstraint(fields=('edition', 'revision'), name='unique_catalog_publication_revision'),
        ),
        migrations.AddConstraint(
            model_name='catalogpublicationrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('edition',), name='one_active_catalog_revision'),
        ),
        migrations.AddIndex(
            model_name='catalogfielddecision',
            index=models.Index(fields=['edition', 'status'], name='catalog_cat_edition_e60001_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogfielddecision',
            index=models.Index(fields=['target_type', 'target_id', 'status'], name='catalog_cat_target__240adf_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogfielddecision',
            constraint=models.UniqueConstraint(fields=('context_type', 'context_id', 'target_type', 'target_id', 'field_name'), name='unique_catalog_field_decision'),
        ),
        migrations.AddConstraint(
            model_name='publicationbundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'object_type', 'object_id'), name='unique_publication_bundle_item'),
        ),
        migrations.RunPython(
            backfill_published_catalog_revisions,
            noop_reverse,
        ),
        migrations.RunPython(backfill_confirmed_draft_bundles, noop_reverse),
    ]
