# Generated by Django 5.2.16 on 2026-09-06 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_v304_journal_issue_articles'),
        ('ingestion', '0014_alter_entityresolutioncandidate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('upload', '上传文献'), ('manual', '手工编目'), ('import', '导入书目'), ('existing', '编辑馆藏')], max_length=16)),
                ('status', models.CharField(choices=[('drafting', '编目中'), ('reviewing', '核对中'), ('ready', '准备发布'), ('publishing', '发布中'), ('published', '已发布'), ('abandoned', '已结束编辑')], default='drafting', max_length=16)),
                ('request_key', models.UUIDField(blank=True, null=True)),
                ('base_public_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_cataloging_sessions', to='catalog.catalogpublicationrevision')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataloging_sessions', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cataloging_sessions', to='catalog.edition')),
                ('upload_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cataloging_sessions', to='ingestion.uploaditem')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='catalog_session_status_updated')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['drafting', 'reviewing', 'ready', 'publishing'])), fields=('edition',), name='one_open_catalog_session_edition'), models.UniqueConstraint(condition=models.Q(('status__in', ['drafting', 'reviewing', 'ready', 'publishing'])), fields=('upload_item',), name='one_open_catalog_session_upload'), models.UniqueConstraint(fields=('created_by', 'request_key'), name='catalog_session_request_key'), models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'upload'), _negated=True), ('upload_item__isnull', False), _connector='OR'), name='upload_catalog_session_has_item'), models.CheckConstraint(condition=models.Q(('upload_item__isnull', False), ('edition__isnull', False), _connector='OR'), name='catalog_session_has_context')],
            },
        ),
    ]
