# Generated by Django 5.2.16 on 2026-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_v305_cataloging_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='publication_mode',
            field=models.CharField(choices=[('document', '书目与文献'), ('bibliographic', '纯书目')], default='document', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.CheckConstraint(condition=models.Q(('publication_mode__in', ['document', 'bibliographic'])), name='edition_publication_mode_valid'),
        ),
    ]
