# Generated by Django 5.2.16 on 2026-09-07 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_v305_bibliographic_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='private/media/originals/%Y/%m/')),
                ('media_type', models.CharField(max_length=40)),
                ('source_type', models.CharField(default='upload', max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_label', models.CharField(blank=True, max_length=300)),
                ('rights', models.TextField(blank=True)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('credit', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=1000)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('focal_x', models.FloatField(default=0.5)),
                ('focal_y', models.FloatField(default=0.5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaRendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_key', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('requested_width', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='private/media/renditions/%Y/%m/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='catalog.mediaasset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('focal_x__gte', 0), ('focal_x__lte', 1), ('focal_y__gte', 0), ('focal_y__lte', 1)), name='media_focal_in_bounds'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0)), name='media_dimensions_positive'),
        ),
        migrations.AddConstraint(
            model_name='mediarendition',
            constraint=models.UniqueConstraint(fields=('media', 'variant_key'), name='unique_media_rendition'),
        ),
    ]
