# Generated by Django 5.2.16 on 2026-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_v305_media_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='source_type',
            field=models.CharField(choices=[('upload', '人工上传'), ('pdf', '文献页面'), ('external', '外部资料'), ('generated', '生成图片')], default='upload', max_length=32),
        ),
    ]
