# Generated by Django 5.2.16 on 2026-09-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_v305_media_source_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarendition',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='cover_rendition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_works', to='catalog.mediarendition'),
        ),
    ]
