# Generated by Django 5.2.16 on 2026-09-08 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_v305_work_media_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPublicationMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_references', to='catalog.catalogpublicationrevision')),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_references', to='catalog.mediarendition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('catalog_revision', 'rendition'), name='unique_catalog_publication_media')],
            },
        ),
    ]
