# Generated by Django 5.2.16 on 2026-09-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_v305_publication_media_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarendition',
            name='metadata_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
