# Generated by Django 5.2.16 on 2026-09-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_v305_media_metadata_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='recommendation_rendition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_works', to='catalog.mediarendition'),
        ),
    ]
