# Generated by Django 5.2.16 on 2026-09-11 04:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_v305_recommendation_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMergeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('preview_fingerprint', models.CharField(max_length=64)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('target_snapshot', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('affected_edition_ids', models.JSONField(default=list)),
                ('event_ids', models.JSONField(default=list)),
                ('rollback_fingerprint', models.CharField(max_length=64)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_merges', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_merge_rollbacks', to=settings.AUTH_USER_MODEL)),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_merge_records', to='catalog.person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_merge_records', to='catalog.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_person', models.F('target_person')), _negated=True), name='person_merge_record_distinct')],
            },
        ),
    ]
