# Generated by Django 5.2.16 on 2026-09-11 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_v305_person_merge_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait_rendition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_portraits', to='catalog.mediarendition'),
        ),
        migrations.CreateModel(
            name='EditorialRevisionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editorial_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_references', to='catalog.editorialrevision')),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_references', to='catalog.mediarendition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('editorial_revision', 'rendition'), name='unique_editorial_revision_media')],
            },
        ),
    ]
