# Generated by Django 5.2.16 on 2026-09-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_v305_scholar_portrait_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenode',
            name='cover_rendition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_node_covers', to='catalog.mediarendition'),
        ),
        migrations.AddField(
            model_name='readingpath',
            name='cover_rendition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading_path_covers', to='catalog.mediarendition'),
        ),
    ]
