# Generated by Django 5.2.16 on 2026-09-20 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_v307_editorial_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialrevision',
            name='target_type',
            field=models.CharField(choices=[('work', '作品'), ('edition', '版本'), ('knowledge_node', '知识节点'), ('scholar_profile', '学者'), ('discipline', '学科'), ('subdiscipline', '子学科'), ('topic', '主题'), ('publisher', '出版社'), ('reading_path', '阅读路径'), ('knowledge_relation', '理论关系'), ('timeline_event', '时间线事件'), ('recommendation_issue', '书库推荐期'), ('site_content', '网站与关于书库'), ('evidence_curation', '原文策展'), ('scholar_relation', '学者关系')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EvidenceCuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('topic', '主题'), ('scholar', '学者'), ('node', '理论与概念')], max_length=16)),
                ('object_id', models.UUIDField()),
                ('active_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_evidence_curations', to='catalog.editorialrevision')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCurationReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='catalog.evidencecuration')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curation_references', to='catalog.passage')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curation_references', to='catalog.evidencespan')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(max_length=32)),
                ('direction', models.CharField(default='directed', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('active_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_scholar_relations', to='catalog.editorialrevision')),
                ('source_scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_shared_relations', to='catalog.scholarprofile')),
                ('target_scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shared_relations', to='catalog.scholarprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evidencecuration',
            constraint=models.UniqueConstraint(fields=('object_type', 'object_id'), name='unique_evidence_curation_target'),
        ),
        migrations.AddConstraint(
            model_name='evidencecurationreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('passage__isnull', True), ('span__isnull', False)), models.Q(('passage__isnull', False), ('span__isnull', True)), _connector='OR'), name='curation_reference_one_source'),
        ),
        migrations.AddConstraint(
            model_name='scholarrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source_scholar', models.F('target_scholar')), _negated=True), name='scholar_relation_distinct_ends'),
        ),
    ]
