# Generated by Django 5.2.16 on 2026-09-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_v307_shared_curation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecurationreference',
            name='document_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curation_references', to='catalog.documentrevision'),
        ),
    ]
