# Generated by Django 5.2.16 on 2026-09-23 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_semantic_index_family_database_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='normalized_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='semanticchunk',
            name='normalized_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RecycleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=600)),
                ('before', models.JSONField(default=dict)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycled_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['model_label', 'restored_at'], name='recycle_active_objects')],
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_id'), name='unique_recycle_object')],
            },
        ),
    ]
