# Generated by Django 5.x on 2026-10-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0063_reversible_records_and_long_text_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="download_default_edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="download_default_for_works",
                to="catalog.edition",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="reader_default_edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reader_default_for_works",
                to="catalog.edition",
            ),
        ),
    ]
