from django.urls import path

from .views import (
    BatchDetailView,
    BatchCreateView,
    BatchItemFailureView,
    BatchItemChunkUploadView,
    BatchItemUploadView,
    BatchListView,
    BatchUploadView,
    DashboardView,
    DeleteUploadItemView,
    EntityResolutionDecisionView,
    EntityResolutionDecisionRevertView,
    MetadataSuggestionRefreshView,
    MetadataCandidateDecisionView,
    MetadataImportView,
    MetadataReviewView,
    ProcessingCenterView,
    SystemHealthView,
    PublishUploadItemView,
    PublicationPlaceReviewView,
    QueueHealthView,
    R2StagingPartConfirmView,
    R2StagingPartFailureView,
    R2StagingPartSignView,
    R2StagingRetryImportView,
    R2StagingUploadAbortView,
    R2StagingUploadCompleteView,
    R2StagingUploadDetailView,
    R2StagingUploadInitView,
    R2StagingUploadListView,
    ReplaceUploadItemView,
    ReviewTaskActionView,
    ReviewTaskListView,
    ResumeUploadItemView,
    RetryUploadItemView,
    UploadItemDetailView,
    UploadItemListView,
    UploadItemPreviewView,
    WithdrawUploadItemView,
)

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="ingestion-dashboard"),
    path("queue-health/", QueueHealthView.as_view(), name="ingestion-queue-health"),
    path("processing-center/", ProcessingCenterView.as_view(), name="processing-center"),
    path("review-tasks/", ReviewTaskListView.as_view(), name="review-task-list"),
    path("review-tasks/<uuid:task_id>/action/", ReviewTaskActionView.as_view(), name="review-task-action"),
    path("system-health/", SystemHealthView.as_view(), name="system-health"),
    path("batches/", BatchListView.as_view(), name="batch-list"),
    path("batches/create/", BatchCreateView.as_view(), name="batch-create"),
    path("batches/upload/", BatchUploadView.as_view(), name="batch-upload"),
    path("batches/<uuid:pk>/", BatchDetailView.as_view(), name="batch-detail"),
    path("batches/<uuid:batch_id>/items/", BatchItemUploadView.as_view(), name="batch-item-upload"),
    path("batches/<uuid:batch_id>/chunks/", BatchItemChunkUploadView.as_view(), name="batch-item-chunk-upload"),
    path("batches/<uuid:batch_id>/failures/", BatchItemFailureView.as_view(), name="batch-item-failure"),
    path("uploads/r2/", R2StagingUploadListView.as_view(), name="r2-staging-upload-list"),
    path("uploads/r2/init/", R2StagingUploadInitView.as_view(), name="r2-staging-upload-init"),
    path("uploads/r2/<uuid:session_id>/", R2StagingUploadDetailView.as_view(), name="r2-staging-upload-detail"),
    path("uploads/r2/<uuid:session_id>/parts/sign/", R2StagingPartSignView.as_view(), name="r2-staging-part-sign"),
    path("uploads/r2/<uuid:session_id>/parts/confirm/", R2StagingPartConfirmView.as_view(), name="r2-staging-part-confirm"),
    path("uploads/r2/<uuid:session_id>/parts/failure/", R2StagingPartFailureView.as_view(), name="r2-staging-part-failure"),
    path("uploads/r2/<uuid:session_id>/complete/", R2StagingUploadCompleteView.as_view(), name="r2-staging-upload-complete"),
    path("uploads/r2/<uuid:session_id>/abort/", R2StagingUploadAbortView.as_view(), name="r2-staging-upload-abort"),
    path("uploads/r2/<uuid:session_id>/retry-import/", R2StagingRetryImportView.as_view(), name="r2-staging-retry-import"),
    path("items/<uuid:pk>/", UploadItemDetailView.as_view(), name="upload-item-detail"),
    path("items/", UploadItemListView.as_view(), name="upload-item-list"),
    path("items/<uuid:pk>/preview/", UploadItemPreviewView.as_view(), name="upload-item-preview"),
    path("items/<uuid:item_id>/retry/", RetryUploadItemView.as_view(), name="upload-item-retry"),
    path("items/<uuid:item_id>/resume/", ResumeUploadItemView.as_view(), name="upload-item-resume"),
    path("items/<uuid:item_id>/replace/", ReplaceUploadItemView.as_view(), name="upload-item-replace"),
    path("items/<uuid:item_id>/review/", MetadataReviewView.as_view(), name="metadata-review"),
    path(
        "items/<uuid:item_id>/metadata-suggestions/",
        MetadataSuggestionRefreshView.as_view(),
        name="metadata-suggestion-refresh",
    ),
    path(
        "items/<uuid:item_id>/metadata-candidates/<uuid:candidate_id>/decision/",
        MetadataCandidateDecisionView.as_view(),
        name="metadata-candidate-decision",
    ),
    path(
        "items/<uuid:item_id>/metadata-import/",
        MetadataImportView.as_view(),
        name="metadata-import",
    ),
    path(
        "items/<uuid:item_id>/entity-resolution-candidates/<uuid:candidate_id>/decision/",
        EntityResolutionDecisionView.as_view(),
        name="entity-resolution-candidate-decision",
    ),
    path(
        "items/<uuid:item_id>/entity-resolution-decisions/<uuid:decision_id>/revert/",
        EntityResolutionDecisionRevertView.as_view(),
        name="entity-resolution-decision-revert",
    ),
    path(
        "items/<uuid:item_id>/publication-places/",
        PublicationPlaceReviewView.as_view(),
        name="publication-place-review",
    ),
    path("items/<uuid:item_id>/publish/", PublishUploadItemView.as_view(), name="upload-item-publish"),
    path("items/<uuid:item_id>/withdraw/", WithdrawUploadItemView.as_view(), name="upload-item-withdraw"),
    path("items/<uuid:item_id>/delete/", DeleteUploadItemView.as_view(), name="upload-item-delete"),
]
